//! Connect to Minecraft servers.

#[cfg(feature = "online-mode")]
pub mod microsoft;
pub mod offline;

use std::{fmt::Debug, ops::Deref, pin::Pin, sync::Arc};

use bevy_ecs::component::Component;
use uuid::Uuid;

/// Something that can join Minecraft servers.
///
/// To join a server using this account, use [`StartJoinServerEvent`] or
/// [`azalea::ClientBuilder`].
///
/// This is also an ECS component that is present on our client entities.
///
/// # Examples
///
/// ```rust,no_run
/// # use azalea_client::Account;
/// #
/// # #[tokio::main]
/// # async fn main() {
/// let account = Account::microsoft("example@example.com").await;
/// // or Account::offline("example");
/// # }
/// ```
///
/// [`StartJoinServerEvent`]: crate::join::StartJoinServerEvent
/// [`azalea::ClientBuilder`]: https://docs.rs/azalea/latest/azalea/struct.ClientBuilder.html
#[derive(Clone, Component, Debug)]
pub struct Account(Arc<dyn AccountTrait>);

pub trait AccountTrait: Send + Sync + Debug {
    /// Returns the Minecraft username of the account.
    fn username(&self) -> &str;
    /// Returns the unique identifier for this player.
    ///
    /// For offline-mode accounts, this UUID is generated by calling
    /// [`azalea_crypto::offline::generate_uuid`].
    fn uuid(&self) -> Uuid;
    /// The access token for authentication.
    ///
    /// You can obtain one of these manually from `azalea-auth`.
    fn access_token(&self) -> Option<String>;

    /// Refreshes the access token for this account.
    #[cfg(feature = "online-mode")]
    fn refresh(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<(), azalea_auth::AuthError>> + Send + '_>> {
        Box::pin(async { Ok(()) })
    }
    /// Refreshes the access token for this account.
    ///
    /// The `online-mode` feature is disabled, so this won't do anything.
    #[cfg(not(feature = "online-mode"))]
    fn refresh(&self) -> Pin<Box<dyn Future<Output = Result<(), ()>> + Send + '_>> {
        Box::pin(async { Ok(()) })
    }

    #[cfg(feature = "online-mode")]
    fn certs(&self) -> Option<azalea_auth::certs::Certificates> {
        None
    }
    /// Override the chat signing certificates for this account.
    ///
    /// You can get the certificates needed for this from
    /// [`azalea_auth::certs::fetch_certificates`]. You typically don't need to
    /// call this yourself, as Azalea will do it for you.
    ///
    /// For accounts that don't support signing (i.e. offline-mode), this won't
    /// do anything.
    #[cfg(feature = "online-mode")]
    fn set_certs(&self, certs: azalea_auth::certs::Certificates) {
        let _ = certs;
    }
}
impl<T: AccountTrait + 'static> From<T> for Account {
    fn from(value: T) -> Self {
        Account(Arc::new(value))
    }
}
impl Deref for Account {
    type Target = dyn AccountTrait;

    fn deref(&self) -> &Self::Target {
        &*self.0
    }
}
