// This file was @generated by codegen/lib/code/tags.py, don't edit it manually!

use std::sync::LazyLock;

use crate::{builtin::EntityKind, tags::RegistryTag};

pub static ACCEPTS_IRON_GOLEM_GIFT: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::CopperGolem]));
pub static AQUATIC: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Axolotl,
        EntityKind::Cod,
        EntityKind::Dolphin,
        EntityKind::ElderGuardian,
        EntityKind::GlowSquid,
        EntityKind::Guardian,
        EntityKind::Nautilus,
        EntityKind::Pufferfish,
        EntityKind::Salmon,
        EntityKind::Squid,
        EntityKind::Tadpole,
        EntityKind::TropicalFish,
        EntityKind::Turtle,
        EntityKind::ZombieNautilus,
    ])
});
pub static ARROWS: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::Arrow, EntityKind::SpectralArrow]));
pub static ARTHROPOD: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Bee,
        EntityKind::CaveSpider,
        EntityKind::Endermite,
        EntityKind::Silverfish,
        EntityKind::Spider,
    ])
});
pub static AXOLOTL_ALWAYS_HOSTILES: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Drowned,
        EntityKind::ElderGuardian,
        EntityKind::Guardian,
    ])
});
pub static AXOLOTL_HUNT_TARGETS: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Cod,
        EntityKind::GlowSquid,
        EntityKind::Pufferfish,
        EntityKind::Salmon,
        EntityKind::Squid,
        EntityKind::Tadpole,
        EntityKind::TropicalFish,
    ])
});
pub static BEEHIVE_INHABITORS: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::Bee]));
pub static BOAT: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::AcaciaBoat,
        EntityKind::BambooRaft,
        EntityKind::BirchBoat,
        EntityKind::CherryBoat,
        EntityKind::DarkOakBoat,
        EntityKind::JungleBoat,
        EntityKind::MangroveBoat,
        EntityKind::OakBoat,
        EntityKind::PaleOakBoat,
        EntityKind::SpruceBoat,
    ])
});
pub static BURN_IN_DAYLIGHT: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Bogged,
        EntityKind::Drowned,
        EntityKind::Phantom,
        EntityKind::Skeleton,
        EntityKind::Stray,
        EntityKind::WitherSkeleton,
        EntityKind::Zombie,
        EntityKind::ZombieHorse,
        EntityKind::ZombieNautilus,
        EntityKind::ZombieVillager,
    ])
});
pub static CAN_BREATHE_UNDER_WATER: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::ArmorStand,
        EntityKind::Axolotl,
        EntityKind::Bogged,
        EntityKind::CamelHusk,
        EntityKind::Cod,
        EntityKind::CopperGolem,
        EntityKind::Drowned,
        EntityKind::ElderGuardian,
        EntityKind::Frog,
        EntityKind::GlowSquid,
        EntityKind::Guardian,
        EntityKind::Husk,
        EntityKind::Nautilus,
        EntityKind::Parched,
        EntityKind::Phantom,
        EntityKind::Pufferfish,
        EntityKind::Salmon,
        EntityKind::Skeleton,
        EntityKind::SkeletonHorse,
        EntityKind::Squid,
        EntityKind::Stray,
        EntityKind::Tadpole,
        EntityKind::TropicalFish,
        EntityKind::Turtle,
        EntityKind::Wither,
        EntityKind::WitherSkeleton,
        EntityKind::Zoglin,
        EntityKind::Zombie,
        EntityKind::ZombieHorse,
        EntityKind::ZombieNautilus,
        EntityKind::ZombieVillager,
        EntityKind::ZombifiedPiglin,
    ])
});
pub static CAN_EQUIP_HARNESS: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::HappyGhast]));
pub static CAN_EQUIP_SADDLE: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Camel,
        EntityKind::CamelHusk,
        EntityKind::Donkey,
        EntityKind::Horse,
        EntityKind::Mule,
        EntityKind::Nautilus,
        EntityKind::Pig,
        EntityKind::SkeletonHorse,
        EntityKind::Strider,
        EntityKind::ZombieHorse,
        EntityKind::ZombieNautilus,
    ])
});
pub static CAN_FLOAT_WHILE_RIDDEN: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Camel,
        EntityKind::CamelHusk,
        EntityKind::Donkey,
        EntityKind::Horse,
        EntityKind::Mule,
        EntityKind::ZombieHorse,
    ])
});
pub static CAN_TURN_IN_BOATS: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::Breeze]));
pub static CAN_WEAR_HORSE_ARMOR: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::Horse, EntityKind::ZombieHorse]));
pub static CAN_WEAR_NAUTILUS_ARMOR: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::Nautilus, EntityKind::ZombieNautilus]));
pub static CANDIDATE_FOR_IRON_GOLEM_GIFT: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::CopperGolem, EntityKind::Villager]));
pub static CANNOT_BE_PUSHED_ONTO_BOATS: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Cod,
        EntityKind::Creaking,
        EntityKind::Dolphin,
        EntityKind::ElderGuardian,
        EntityKind::GlowSquid,
        EntityKind::Nautilus,
        EntityKind::Pufferfish,
        EntityKind::Salmon,
        EntityKind::Squid,
        EntityKind::Tadpole,
        EntityKind::TropicalFish,
        EntityKind::ZombieNautilus,
        EntityKind::Player,
    ])
});
pub static DEFLECTS_PROJECTILES: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::Breeze]));
pub static DISMOUNTS_UNDERWATER: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Camel,
        EntityKind::Chicken,
        EntityKind::Donkey,
        EntityKind::HappyGhast,
        EntityKind::Horse,
        EntityKind::Llama,
        EntityKind::Mule,
        EntityKind::Pig,
        EntityKind::Ravager,
        EntityKind::Spider,
        EntityKind::Strider,
        EntityKind::TraderLlama,
        EntityKind::ZombieHorse,
    ])
});
pub static FALL_DAMAGE_IMMUNE: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Allay,
        EntityKind::Bat,
        EntityKind::Bee,
        EntityKind::Blaze,
        EntityKind::Breeze,
        EntityKind::Cat,
        EntityKind::Chicken,
        EntityKind::CopperGolem,
        EntityKind::Ghast,
        EntityKind::HappyGhast,
        EntityKind::IronGolem,
        EntityKind::MagmaCube,
        EntityKind::Ocelot,
        EntityKind::Parrot,
        EntityKind::Phantom,
        EntityKind::Shulker,
        EntityKind::SnowGolem,
        EntityKind::Wither,
    ])
});
pub static FOLLOWABLE_FRIENDLY_MOBS: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Armadillo,
        EntityKind::Bee,
        EntityKind::Camel,
        EntityKind::Cat,
        EntityKind::Chicken,
        EntityKind::Cow,
        EntityKind::Donkey,
        EntityKind::Fox,
        EntityKind::HappyGhast,
        EntityKind::Goat,
        EntityKind::Horse,
        EntityKind::Llama,
        EntityKind::Mule,
        EntityKind::Ocelot,
        EntityKind::Panda,
        EntityKind::Parrot,
        EntityKind::Pig,
        EntityKind::PolarBear,
        EntityKind::Rabbit,
        EntityKind::Sheep,
        EntityKind::SkeletonHorse,
        EntityKind::Sniffer,
        EntityKind::Strider,
        EntityKind::Villager,
        EntityKind::Wolf,
    ])
});
pub static FREEZE_HURTS_EXTRA_TYPES: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Blaze,
        EntityKind::MagmaCube,
        EntityKind::Strider,
    ])
});
pub static FREEZE_IMMUNE_ENTITY_TYPES: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::PolarBear,
        EntityKind::SnowGolem,
        EntityKind::Stray,
        EntityKind::Wither,
    ])
});
pub static FROG_FOOD: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::MagmaCube, EntityKind::Slime]));
pub static IGNORES_POISON_AND_REGEN: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Bogged,
        EntityKind::CamelHusk,
        EntityKind::Drowned,
        EntityKind::Husk,
        EntityKind::Parched,
        EntityKind::Phantom,
        EntityKind::Skeleton,
        EntityKind::SkeletonHorse,
        EntityKind::Stray,
        EntityKind::Wither,
        EntityKind::WitherSkeleton,
        EntityKind::Zoglin,
        EntityKind::Zombie,
        EntityKind::ZombieHorse,
        EntityKind::ZombieNautilus,
        EntityKind::ZombieVillager,
        EntityKind::ZombifiedPiglin,
    ])
});
pub static ILLAGER: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Evoker,
        EntityKind::Illusioner,
        EntityKind::Pillager,
        EntityKind::Vindicator,
    ])
});
pub static ILLAGER_FRIENDS: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Evoker,
        EntityKind::Illusioner,
        EntityKind::Pillager,
        EntityKind::Vindicator,
    ])
});
pub static IMMUNE_TO_INFESTED: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::Silverfish]));
pub static IMMUNE_TO_OOZING: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::Slime]));
pub static IMPACT_PROJECTILES: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Arrow,
        EntityKind::BreezeWindCharge,
        EntityKind::DragonFireball,
        EntityKind::Egg,
        EntityKind::Fireball,
        EntityKind::FireworkRocket,
        EntityKind::SmallFireball,
        EntityKind::Snowball,
        EntityKind::SpectralArrow,
        EntityKind::Trident,
        EntityKind::WindCharge,
        EntityKind::WitherSkull,
    ])
});
pub static INVERTED_HEALING_AND_HARM: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Bogged,
        EntityKind::CamelHusk,
        EntityKind::Drowned,
        EntityKind::Husk,
        EntityKind::Parched,
        EntityKind::Phantom,
        EntityKind::Skeleton,
        EntityKind::SkeletonHorse,
        EntityKind::Stray,
        EntityKind::Wither,
        EntityKind::WitherSkeleton,
        EntityKind::Zoglin,
        EntityKind::Zombie,
        EntityKind::ZombieHorse,
        EntityKind::ZombieNautilus,
        EntityKind::ZombieVillager,
        EntityKind::ZombifiedPiglin,
    ])
});
pub static NAUTILUS_HOSTILES: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::Pufferfish]));
pub static NO_ANGER_FROM_WIND_CHARGE: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Bogged,
        EntityKind::Breeze,
        EntityKind::CaveSpider,
        EntityKind::Husk,
        EntityKind::Skeleton,
        EntityKind::Slime,
        EntityKind::Spider,
        EntityKind::Stray,
        EntityKind::Zombie,
    ])
});
pub static NON_CONTROLLING_RIDER: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| RegistryTag::new(vec![EntityKind::MagmaCube, EntityKind::Slime]));
pub static NOT_SCARY_FOR_PUFFERFISH: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Cod,
        EntityKind::Dolphin,
        EntityKind::ElderGuardian,
        EntityKind::GlowSquid,
        EntityKind::Guardian,
        EntityKind::Nautilus,
        EntityKind::Pufferfish,
        EntityKind::Salmon,
        EntityKind::Squid,
        EntityKind::Tadpole,
        EntityKind::TropicalFish,
        EntityKind::Turtle,
        EntityKind::ZombieNautilus,
    ])
});
pub static POWDER_SNOW_WALKABLE_MOBS: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Endermite,
        EntityKind::Fox,
        EntityKind::Rabbit,
        EntityKind::Silverfish,
    ])
});
pub static RAIDERS: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Evoker,
        EntityKind::Illusioner,
        EntityKind::Pillager,
        EntityKind::Ravager,
        EntityKind::Vindicator,
        EntityKind::Witch,
    ])
});
pub static REDIRECTABLE_PROJECTILE: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::BreezeWindCharge,
        EntityKind::Fireball,
        EntityKind::WindCharge,
    ])
});
pub static SENSITIVE_TO_BANE_OF_ARTHROPODS: LazyLock<RegistryTag<EntityKind>> =
    LazyLock::new(|| {
        RegistryTag::new(vec![
            EntityKind::Bee,
            EntityKind::CaveSpider,
            EntityKind::Endermite,
            EntityKind::Silverfish,
            EntityKind::Spider,
        ])
    });
pub static SENSITIVE_TO_IMPALING: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Axolotl,
        EntityKind::Cod,
        EntityKind::Dolphin,
        EntityKind::ElderGuardian,
        EntityKind::GlowSquid,
        EntityKind::Guardian,
        EntityKind::Nautilus,
        EntityKind::Pufferfish,
        EntityKind::Salmon,
        EntityKind::Squid,
        EntityKind::Tadpole,
        EntityKind::TropicalFish,
        EntityKind::Turtle,
        EntityKind::ZombieNautilus,
    ])
});
pub static SENSITIVE_TO_SMITE: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Bogged,
        EntityKind::CamelHusk,
        EntityKind::Drowned,
        EntityKind::Husk,
        EntityKind::Parched,
        EntityKind::Phantom,
        EntityKind::Skeleton,
        EntityKind::SkeletonHorse,
        EntityKind::Stray,
        EntityKind::Wither,
        EntityKind::WitherSkeleton,
        EntityKind::Zoglin,
        EntityKind::Zombie,
        EntityKind::ZombieHorse,
        EntityKind::ZombieNautilus,
        EntityKind::ZombieVillager,
        EntityKind::ZombifiedPiglin,
    ])
});
pub static SKELETONS: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Bogged,
        EntityKind::Parched,
        EntityKind::Skeleton,
        EntityKind::SkeletonHorse,
        EntityKind::Stray,
        EntityKind::WitherSkeleton,
    ])
});
pub static UNDEAD: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Bogged,
        EntityKind::CamelHusk,
        EntityKind::Drowned,
        EntityKind::Husk,
        EntityKind::Parched,
        EntityKind::Phantom,
        EntityKind::Skeleton,
        EntityKind::SkeletonHorse,
        EntityKind::Stray,
        EntityKind::Wither,
        EntityKind::WitherSkeleton,
        EntityKind::Zoglin,
        EntityKind::Zombie,
        EntityKind::ZombieHorse,
        EntityKind::ZombieNautilus,
        EntityKind::ZombieVillager,
        EntityKind::ZombifiedPiglin,
    ])
});
pub static WITHER_FRIENDS: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::Bogged,
        EntityKind::CamelHusk,
        EntityKind::Drowned,
        EntityKind::Husk,
        EntityKind::Parched,
        EntityKind::Phantom,
        EntityKind::Skeleton,
        EntityKind::SkeletonHorse,
        EntityKind::Stray,
        EntityKind::Wither,
        EntityKind::WitherSkeleton,
        EntityKind::Zoglin,
        EntityKind::Zombie,
        EntityKind::ZombieHorse,
        EntityKind::ZombieNautilus,
        EntityKind::ZombieVillager,
        EntityKind::ZombifiedPiglin,
    ])
});
pub static ZOMBIES: LazyLock<RegistryTag<EntityKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        EntityKind::CamelHusk,
        EntityKind::Drowned,
        EntityKind::Husk,
        EntityKind::Zoglin,
        EntityKind::Zombie,
        EntityKind::ZombieHorse,
        EntityKind::ZombieNautilus,
        EntityKind::ZombieVillager,
        EntityKind::ZombifiedPiglin,
    ])
});
