// This file was @generated by codegen/lib/code/tags.py, don't edit it manually!

use std::sync::LazyLock;

use crate::{builtin::Fluid, tags::RegistryTag};

pub static LAVA: LazyLock<RegistryTag<Fluid>> =
    LazyLock::new(|| RegistryTag::new(vec![Fluid::FlowingLava, Fluid::Lava]));
pub static WATER: LazyLock<RegistryTag<Fluid>> =
    LazyLock::new(|| RegistryTag::new(vec![Fluid::FlowingWater, Fluid::Water]));
