// This file was generated by codegen/lib/code/tags.py, don't edit it manually!

use std::{collections::HashSet, sync::LazyLock};

use crate::Fluid;

pub static LAVA: LazyLock<HashSet<Fluid>> =
    LazyLock::new(|| HashSet::from_iter(vec![Fluid::Lava, Fluid::FlowingLava]));
pub static WATER: LazyLock<HashSet<Fluid>> =
    LazyLock::new(|| HashSet::from_iter(vec![Fluid::Water, Fluid::FlowingWater]));
