// This file was @generated by codegen/lib/code/tags.py, don't edit it manually!

use std::sync::LazyLock;

use crate::{builtin::ItemKind, tags::RegistryTag};

pub static ACACIA_LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::AcaciaLog,
        ItemKind::StrippedAcaciaLog,
        ItemKind::StrippedAcaciaWood,
        ItemKind::AcaciaWood,
    ])
});
pub static ANVIL: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Anvil,
        ItemKind::ChippedAnvil,
        ItemKind::DamagedAnvil,
    ])
});
pub static ARMADILLO_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::SpiderEye]));
pub static ARROWS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Arrow,
        ItemKind::SpectralArrow,
        ItemKind::TippedArrow,
    ])
});
pub static AXES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenAxe,
        ItemKind::CopperAxe,
        ItemKind::StoneAxe,
        ItemKind::GoldenAxe,
        ItemKind::IronAxe,
        ItemKind::DiamondAxe,
        ItemKind::NetheriteAxe,
    ])
});
pub static AXOLOTL_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::TropicalFishBucket]));
pub static BAMBOO_BLOCKS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::BambooBlock, ItemKind::StrippedBambooBlock]));
pub static BANNERS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WhiteBanner,
        ItemKind::OrangeBanner,
        ItemKind::MagentaBanner,
        ItemKind::LightBlueBanner,
        ItemKind::YellowBanner,
        ItemKind::LimeBanner,
        ItemKind::PinkBanner,
        ItemKind::GrayBanner,
        ItemKind::LightGrayBanner,
        ItemKind::CyanBanner,
        ItemKind::PurpleBanner,
        ItemKind::BlueBanner,
        ItemKind::BrownBanner,
        ItemKind::GreenBanner,
        ItemKind::RedBanner,
        ItemKind::BlackBanner,
    ])
});
pub static BARS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::IronBars,
        ItemKind::CopperBars,
        ItemKind::ExposedCopperBars,
        ItemKind::WeatheredCopperBars,
        ItemKind::OxidizedCopperBars,
        ItemKind::WaxedCopperBars,
        ItemKind::WaxedExposedCopperBars,
        ItemKind::WaxedWeatheredCopperBars,
        ItemKind::WaxedOxidizedCopperBars,
    ])
});
pub static BEACON_PAYMENT_ITEMS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Diamond,
        ItemKind::Emerald,
        ItemKind::IronIngot,
        ItemKind::GoldIngot,
        ItemKind::NetheriteIngot,
    ])
});
pub static BEDS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WhiteBed,
        ItemKind::OrangeBed,
        ItemKind::MagentaBed,
        ItemKind::LightBlueBed,
        ItemKind::YellowBed,
        ItemKind::LimeBed,
        ItemKind::PinkBed,
        ItemKind::GrayBed,
        ItemKind::LightGrayBed,
        ItemKind::CyanBed,
        ItemKind::PurpleBed,
        ItemKind::BlueBed,
        ItemKind::BrownBed,
        ItemKind::GreenBed,
        ItemKind::RedBed,
        ItemKind::BlackBed,
    ])
});
pub static BEE_FOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::MangrovePropagule,
        ItemKind::CherryLeaves,
        ItemKind::FloweringAzaleaLeaves,
        ItemKind::FloweringAzalea,
        ItemKind::Dandelion,
        ItemKind::OpenEyeblossom,
        ItemKind::Poppy,
        ItemKind::BlueOrchid,
        ItemKind::Allium,
        ItemKind::AzureBluet,
        ItemKind::RedTulip,
        ItemKind::OrangeTulip,
        ItemKind::WhiteTulip,
        ItemKind::PinkTulip,
        ItemKind::OxeyeDaisy,
        ItemKind::Cornflower,
        ItemKind::LilyOfTheValley,
        ItemKind::WitherRose,
        ItemKind::Torchflower,
        ItemKind::PitcherPlant,
        ItemKind::SporeBlossom,
        ItemKind::PinkPetals,
        ItemKind::Wildflowers,
        ItemKind::ChorusFlower,
        ItemKind::CactusFlower,
        ItemKind::Sunflower,
        ItemKind::Lilac,
        ItemKind::RoseBush,
        ItemKind::Peony,
    ])
});
pub static BIRCH_LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::BirchLog,
        ItemKind::StrippedBirchLog,
        ItemKind::StrippedBirchWood,
        ItemKind::BirchWood,
    ])
});
pub static BOATS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakBoat,
        ItemKind::OakChestBoat,
        ItemKind::SpruceBoat,
        ItemKind::SpruceChestBoat,
        ItemKind::BirchBoat,
        ItemKind::BirchChestBoat,
        ItemKind::JungleBoat,
        ItemKind::JungleChestBoat,
        ItemKind::AcaciaBoat,
        ItemKind::AcaciaChestBoat,
        ItemKind::CherryBoat,
        ItemKind::CherryChestBoat,
        ItemKind::DarkOakBoat,
        ItemKind::DarkOakChestBoat,
        ItemKind::PaleOakBoat,
        ItemKind::PaleOakChestBoat,
        ItemKind::MangroveBoat,
        ItemKind::MangroveChestBoat,
        ItemKind::BambooRaft,
        ItemKind::BambooChestRaft,
    ])
});
pub static BOOK_CLONING_TARGET: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::WritableBook]));
pub static BOOKSHELF_BOOKS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Book,
        ItemKind::WritableBook,
        ItemKind::WrittenBook,
        ItemKind::EnchantedBook,
        ItemKind::KnowledgeBook,
    ])
});
pub static BREAKS_DECORATED_POTS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenSword,
        ItemKind::WoodenShovel,
        ItemKind::WoodenPickaxe,
        ItemKind::WoodenAxe,
        ItemKind::WoodenHoe,
        ItemKind::CopperSword,
        ItemKind::CopperShovel,
        ItemKind::CopperPickaxe,
        ItemKind::CopperAxe,
        ItemKind::CopperHoe,
        ItemKind::StoneSword,
        ItemKind::StoneShovel,
        ItemKind::StonePickaxe,
        ItemKind::StoneAxe,
        ItemKind::StoneHoe,
        ItemKind::GoldenSword,
        ItemKind::GoldenShovel,
        ItemKind::GoldenPickaxe,
        ItemKind::GoldenAxe,
        ItemKind::GoldenHoe,
        ItemKind::IronSword,
        ItemKind::IronShovel,
        ItemKind::IronPickaxe,
        ItemKind::IronAxe,
        ItemKind::IronHoe,
        ItemKind::DiamondSword,
        ItemKind::DiamondShovel,
        ItemKind::DiamondPickaxe,
        ItemKind::DiamondAxe,
        ItemKind::DiamondHoe,
        ItemKind::NetheriteSword,
        ItemKind::NetheriteShovel,
        ItemKind::NetheritePickaxe,
        ItemKind::NetheriteAxe,
        ItemKind::NetheriteHoe,
        ItemKind::Mace,
        ItemKind::Trident,
    ])
});
pub static BREWING_FUEL: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::BlazePowder]));
pub static BUNDLES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Bundle,
        ItemKind::WhiteBundle,
        ItemKind::OrangeBundle,
        ItemKind::MagentaBundle,
        ItemKind::LightBlueBundle,
        ItemKind::YellowBundle,
        ItemKind::LimeBundle,
        ItemKind::PinkBundle,
        ItemKind::GrayBundle,
        ItemKind::LightGrayBundle,
        ItemKind::CyanBundle,
        ItemKind::PurpleBundle,
        ItemKind::BlueBundle,
        ItemKind::BrownBundle,
        ItemKind::GreenBundle,
        ItemKind::RedBundle,
        ItemKind::BlackBundle,
    ])
});
pub static BUTTONS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::StoneButton,
        ItemKind::PolishedBlackstoneButton,
        ItemKind::OakButton,
        ItemKind::SpruceButton,
        ItemKind::BirchButton,
        ItemKind::JungleButton,
        ItemKind::AcaciaButton,
        ItemKind::CherryButton,
        ItemKind::DarkOakButton,
        ItemKind::PaleOakButton,
        ItemKind::MangroveButton,
        ItemKind::BambooButton,
        ItemKind::CrimsonButton,
        ItemKind::WarpedButton,
    ])
});
pub static CAMEL_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Cactus]));
pub static CAMEL_HUSK_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::RabbitFoot]));
pub static CANDLES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Candle,
        ItemKind::WhiteCandle,
        ItemKind::OrangeCandle,
        ItemKind::MagentaCandle,
        ItemKind::LightBlueCandle,
        ItemKind::YellowCandle,
        ItemKind::LimeCandle,
        ItemKind::PinkCandle,
        ItemKind::GrayCandle,
        ItemKind::LightGrayCandle,
        ItemKind::CyanCandle,
        ItemKind::PurpleCandle,
        ItemKind::BlueCandle,
        ItemKind::BrownCandle,
        ItemKind::GreenCandle,
        ItemKind::RedCandle,
        ItemKind::BlackCandle,
    ])
});
pub static CAT_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Cod, ItemKind::Salmon]));
pub static CHAINS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::IronChain,
        ItemKind::CopperChain,
        ItemKind::ExposedCopperChain,
        ItemKind::WeatheredCopperChain,
        ItemKind::OxidizedCopperChain,
        ItemKind::WaxedCopperChain,
        ItemKind::WaxedExposedCopperChain,
        ItemKind::WaxedWeatheredCopperChain,
        ItemKind::WaxedOxidizedCopperChain,
    ])
});
pub static CHERRY_LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CherryLog,
        ItemKind::StrippedCherryLog,
        ItemKind::StrippedCherryWood,
        ItemKind::CherryWood,
    ])
});
pub static CHEST_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::LeatherChestplate,
        ItemKind::CopperChestplate,
        ItemKind::ChainmailChestplate,
        ItemKind::IronChestplate,
        ItemKind::DiamondChestplate,
        ItemKind::GoldenChestplate,
        ItemKind::NetheriteChestplate,
    ])
});
pub static CHEST_BOATS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakChestBoat,
        ItemKind::SpruceChestBoat,
        ItemKind::BirchChestBoat,
        ItemKind::JungleChestBoat,
        ItemKind::AcaciaChestBoat,
        ItemKind::CherryChestBoat,
        ItemKind::DarkOakChestBoat,
        ItemKind::PaleOakChestBoat,
        ItemKind::MangroveChestBoat,
        ItemKind::BambooChestRaft,
    ])
});
pub static CHICKEN_FOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WheatSeeds,
        ItemKind::PumpkinSeeds,
        ItemKind::MelonSeeds,
        ItemKind::TorchflowerSeeds,
        ItemKind::PitcherPod,
        ItemKind::BeetrootSeeds,
    ])
});
pub static CLUSTER_MAX_HARVESTABLES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenPickaxe,
        ItemKind::CopperPickaxe,
        ItemKind::StonePickaxe,
        ItemKind::GoldenPickaxe,
        ItemKind::IronPickaxe,
        ItemKind::DiamondPickaxe,
        ItemKind::NetheritePickaxe,
    ])
});
pub static COAL_ORES: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::CoalOre, ItemKind::DeepslateCoalOre]));
pub static COALS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Coal, ItemKind::Charcoal]));
pub static COMPASSES: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Compass, ItemKind::RecoveryCompass]));
pub static COMPLETES_FIND_TREE_TUTORIAL: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakLog,
        ItemKind::SpruceLog,
        ItemKind::BirchLog,
        ItemKind::JungleLog,
        ItemKind::AcaciaLog,
        ItemKind::CherryLog,
        ItemKind::PaleOakLog,
        ItemKind::DarkOakLog,
        ItemKind::MangroveLog,
        ItemKind::CrimsonStem,
        ItemKind::WarpedStem,
        ItemKind::StrippedOakLog,
        ItemKind::StrippedSpruceLog,
        ItemKind::StrippedBirchLog,
        ItemKind::StrippedJungleLog,
        ItemKind::StrippedAcaciaLog,
        ItemKind::StrippedCherryLog,
        ItemKind::StrippedDarkOakLog,
        ItemKind::StrippedPaleOakLog,
        ItemKind::StrippedMangroveLog,
        ItemKind::StrippedCrimsonStem,
        ItemKind::StrippedWarpedStem,
        ItemKind::StrippedOakWood,
        ItemKind::StrippedSpruceWood,
        ItemKind::StrippedBirchWood,
        ItemKind::StrippedJungleWood,
        ItemKind::StrippedAcaciaWood,
        ItemKind::StrippedCherryWood,
        ItemKind::StrippedDarkOakWood,
        ItemKind::StrippedPaleOakWood,
        ItemKind::StrippedMangroveWood,
        ItemKind::StrippedCrimsonHyphae,
        ItemKind::StrippedWarpedHyphae,
        ItemKind::OakWood,
        ItemKind::SpruceWood,
        ItemKind::BirchWood,
        ItemKind::JungleWood,
        ItemKind::AcaciaWood,
        ItemKind::CherryWood,
        ItemKind::PaleOakWood,
        ItemKind::DarkOakWood,
        ItemKind::MangroveWood,
        ItemKind::CrimsonHyphae,
        ItemKind::WarpedHyphae,
        ItemKind::OakLeaves,
        ItemKind::SpruceLeaves,
        ItemKind::BirchLeaves,
        ItemKind::JungleLeaves,
        ItemKind::AcaciaLeaves,
        ItemKind::CherryLeaves,
        ItemKind::DarkOakLeaves,
        ItemKind::PaleOakLeaves,
        ItemKind::MangroveLeaves,
        ItemKind::AzaleaLeaves,
        ItemKind::FloweringAzaleaLeaves,
        ItemKind::NetherWartBlock,
        ItemKind::WarpedWartBlock,
    ])
});
pub static COPPER: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CopperBlock,
        ItemKind::ExposedCopper,
        ItemKind::WeatheredCopper,
        ItemKind::OxidizedCopper,
        ItemKind::WaxedCopperBlock,
        ItemKind::WaxedExposedCopper,
        ItemKind::WaxedWeatheredCopper,
        ItemKind::WaxedOxidizedCopper,
    ])
});
pub static COPPER_CHESTS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CopperChest,
        ItemKind::ExposedCopperChest,
        ItemKind::WeatheredCopperChest,
        ItemKind::OxidizedCopperChest,
        ItemKind::WaxedCopperChest,
        ItemKind::WaxedExposedCopperChest,
        ItemKind::WaxedWeatheredCopperChest,
        ItemKind::WaxedOxidizedCopperChest,
    ])
});
pub static COPPER_GOLEM_STATUES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CopperGolemStatue,
        ItemKind::ExposedCopperGolemStatue,
        ItemKind::WeatheredCopperGolemStatue,
        ItemKind::OxidizedCopperGolemStatue,
        ItemKind::WaxedCopperGolemStatue,
        ItemKind::WaxedExposedCopperGolemStatue,
        ItemKind::WaxedWeatheredCopperGolemStatue,
        ItemKind::WaxedOxidizedCopperGolemStatue,
    ])
});
pub static COPPER_ORES: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::CopperOre, ItemKind::DeepslateCopperOre]));
pub static COPPER_TOOL_MATERIALS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::CopperIngot]));
pub static COW_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Wheat]));
pub static CREEPER_DROP_MUSIC_DISCS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::MusicDisc13,
        ItemKind::MusicDiscCat,
        ItemKind::MusicDiscBlocks,
        ItemKind::MusicDiscChirp,
        ItemKind::MusicDiscFar,
        ItemKind::MusicDiscMall,
        ItemKind::MusicDiscMellohi,
        ItemKind::MusicDiscStal,
        ItemKind::MusicDiscStrad,
        ItemKind::MusicDiscWard,
        ItemKind::MusicDisc11,
        ItemKind::MusicDiscWait,
    ])
});
pub static CREEPER_IGNITERS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::FlintAndSteel, ItemKind::FireCharge]));
pub static CRIMSON_STEMS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CrimsonStem,
        ItemKind::StrippedCrimsonStem,
        ItemKind::StrippedCrimsonHyphae,
        ItemKind::CrimsonHyphae,
    ])
});
pub static DAMPENS_VIBRATIONS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WhiteWool,
        ItemKind::OrangeWool,
        ItemKind::MagentaWool,
        ItemKind::LightBlueWool,
        ItemKind::YellowWool,
        ItemKind::LimeWool,
        ItemKind::PinkWool,
        ItemKind::GrayWool,
        ItemKind::LightGrayWool,
        ItemKind::CyanWool,
        ItemKind::PurpleWool,
        ItemKind::BlueWool,
        ItemKind::BrownWool,
        ItemKind::GreenWool,
        ItemKind::RedWool,
        ItemKind::BlackWool,
        ItemKind::WhiteCarpet,
        ItemKind::OrangeCarpet,
        ItemKind::MagentaCarpet,
        ItemKind::LightBlueCarpet,
        ItemKind::YellowCarpet,
        ItemKind::LimeCarpet,
        ItemKind::PinkCarpet,
        ItemKind::GrayCarpet,
        ItemKind::LightGrayCarpet,
        ItemKind::CyanCarpet,
        ItemKind::PurpleCarpet,
        ItemKind::BlueCarpet,
        ItemKind::BrownCarpet,
        ItemKind::GreenCarpet,
        ItemKind::RedCarpet,
        ItemKind::BlackCarpet,
    ])
});
pub static DARK_OAK_LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::DarkOakLog,
        ItemKind::StrippedDarkOakLog,
        ItemKind::StrippedDarkOakWood,
        ItemKind::DarkOakWood,
    ])
});
pub static DECORATED_POT_INGREDIENTS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Brick,
        ItemKind::AnglerPotterySherd,
        ItemKind::ArcherPotterySherd,
        ItemKind::ArmsUpPotterySherd,
        ItemKind::BladePotterySherd,
        ItemKind::BrewerPotterySherd,
        ItemKind::BurnPotterySherd,
        ItemKind::DangerPotterySherd,
        ItemKind::ExplorerPotterySherd,
        ItemKind::FlowPotterySherd,
        ItemKind::FriendPotterySherd,
        ItemKind::GusterPotterySherd,
        ItemKind::HeartPotterySherd,
        ItemKind::HeartbreakPotterySherd,
        ItemKind::HowlPotterySherd,
        ItemKind::MinerPotterySherd,
        ItemKind::MournerPotterySherd,
        ItemKind::PlentyPotterySherd,
        ItemKind::PrizePotterySherd,
        ItemKind::ScrapePotterySherd,
        ItemKind::SheafPotterySherd,
        ItemKind::ShelterPotterySherd,
        ItemKind::SkullPotterySherd,
        ItemKind::SnortPotterySherd,
    ])
});
pub static DECORATED_POT_SHERDS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::AnglerPotterySherd,
        ItemKind::ArcherPotterySherd,
        ItemKind::ArmsUpPotterySherd,
        ItemKind::BladePotterySherd,
        ItemKind::BrewerPotterySherd,
        ItemKind::BurnPotterySherd,
        ItemKind::DangerPotterySherd,
        ItemKind::ExplorerPotterySherd,
        ItemKind::FlowPotterySherd,
        ItemKind::FriendPotterySherd,
        ItemKind::GusterPotterySherd,
        ItemKind::HeartPotterySherd,
        ItemKind::HeartbreakPotterySherd,
        ItemKind::HowlPotterySherd,
        ItemKind::MinerPotterySherd,
        ItemKind::MournerPotterySherd,
        ItemKind::PlentyPotterySherd,
        ItemKind::PrizePotterySherd,
        ItemKind::ScrapePotterySherd,
        ItemKind::SheafPotterySherd,
        ItemKind::ShelterPotterySherd,
        ItemKind::SkullPotterySherd,
        ItemKind::SnortPotterySherd,
    ])
});
pub static DIAMOND_ORES: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::DiamondOre, ItemKind::DeepslateDiamondOre]));
pub static DIAMOND_TOOL_MATERIALS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Diamond]));
pub static DIRT: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::GrassBlock,
        ItemKind::Dirt,
        ItemKind::CoarseDirt,
        ItemKind::Podzol,
        ItemKind::RootedDirt,
        ItemKind::Mud,
        ItemKind::MuddyMangroveRoots,
        ItemKind::MossBlock,
        ItemKind::PaleMossBlock,
        ItemKind::Mycelium,
    ])
});
pub static DOORS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::IronDoor,
        ItemKind::OakDoor,
        ItemKind::SpruceDoor,
        ItemKind::BirchDoor,
        ItemKind::JungleDoor,
        ItemKind::AcaciaDoor,
        ItemKind::CherryDoor,
        ItemKind::DarkOakDoor,
        ItemKind::PaleOakDoor,
        ItemKind::MangroveDoor,
        ItemKind::BambooDoor,
        ItemKind::CrimsonDoor,
        ItemKind::WarpedDoor,
        ItemKind::CopperDoor,
        ItemKind::ExposedCopperDoor,
        ItemKind::WeatheredCopperDoor,
        ItemKind::OxidizedCopperDoor,
        ItemKind::WaxedCopperDoor,
        ItemKind::WaxedExposedCopperDoor,
        ItemKind::WaxedWeatheredCopperDoor,
        ItemKind::WaxedOxidizedCopperDoor,
    ])
});
pub static DROWNED_PREFERRED_WEAPONS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Trident]));
pub static DUPLICATES_ALLAYS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::AmethystShard]));
pub static DYEABLE: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WolfArmor,
        ItemKind::LeatherHelmet,
        ItemKind::LeatherChestplate,
        ItemKind::LeatherLeggings,
        ItemKind::LeatherBoots,
        ItemKind::LeatherHorseArmor,
    ])
});
pub static EGGS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Egg, ItemKind::BlueEgg, ItemKind::BrownEgg]));
pub static EMERALD_ORES: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::EmeraldOre, ItemKind::DeepslateEmeraldOre]));
pub static ENCHANTABLE_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::TurtleHelmet,
        ItemKind::LeatherHelmet,
        ItemKind::LeatherChestplate,
        ItemKind::LeatherLeggings,
        ItemKind::LeatherBoots,
        ItemKind::CopperHelmet,
        ItemKind::CopperChestplate,
        ItemKind::CopperLeggings,
        ItemKind::CopperBoots,
        ItemKind::ChainmailHelmet,
        ItemKind::ChainmailChestplate,
        ItemKind::ChainmailLeggings,
        ItemKind::ChainmailBoots,
        ItemKind::IronHelmet,
        ItemKind::IronChestplate,
        ItemKind::IronLeggings,
        ItemKind::IronBoots,
        ItemKind::DiamondHelmet,
        ItemKind::DiamondChestplate,
        ItemKind::DiamondLeggings,
        ItemKind::DiamondBoots,
        ItemKind::GoldenHelmet,
        ItemKind::GoldenChestplate,
        ItemKind::GoldenLeggings,
        ItemKind::GoldenBoots,
        ItemKind::NetheriteHelmet,
        ItemKind::NetheriteChestplate,
        ItemKind::NetheriteLeggings,
        ItemKind::NetheriteBoots,
    ])
});
pub static ENCHANTABLE_BOW: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Bow]));
pub static ENCHANTABLE_CHEST_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::LeatherChestplate,
        ItemKind::CopperChestplate,
        ItemKind::ChainmailChestplate,
        ItemKind::IronChestplate,
        ItemKind::DiamondChestplate,
        ItemKind::GoldenChestplate,
        ItemKind::NetheriteChestplate,
    ])
});
pub static ENCHANTABLE_CROSSBOW: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Crossbow]));
pub static ENCHANTABLE_DURABILITY: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CarrotOnAStick,
        ItemKind::WarpedFungusOnAStick,
        ItemKind::Elytra,
        ItemKind::TurtleHelmet,
        ItemKind::FlintAndSteel,
        ItemKind::Bow,
        ItemKind::WoodenSword,
        ItemKind::WoodenShovel,
        ItemKind::WoodenPickaxe,
        ItemKind::WoodenAxe,
        ItemKind::WoodenHoe,
        ItemKind::CopperSword,
        ItemKind::CopperShovel,
        ItemKind::CopperPickaxe,
        ItemKind::CopperAxe,
        ItemKind::CopperHoe,
        ItemKind::StoneSword,
        ItemKind::StoneShovel,
        ItemKind::StonePickaxe,
        ItemKind::StoneAxe,
        ItemKind::StoneHoe,
        ItemKind::GoldenSword,
        ItemKind::GoldenShovel,
        ItemKind::GoldenPickaxe,
        ItemKind::GoldenAxe,
        ItemKind::GoldenHoe,
        ItemKind::IronSword,
        ItemKind::IronShovel,
        ItemKind::IronPickaxe,
        ItemKind::IronAxe,
        ItemKind::IronHoe,
        ItemKind::DiamondSword,
        ItemKind::DiamondShovel,
        ItemKind::DiamondPickaxe,
        ItemKind::DiamondAxe,
        ItemKind::DiamondHoe,
        ItemKind::NetheriteSword,
        ItemKind::NetheriteShovel,
        ItemKind::NetheritePickaxe,
        ItemKind::NetheriteAxe,
        ItemKind::NetheriteHoe,
        ItemKind::LeatherHelmet,
        ItemKind::LeatherChestplate,
        ItemKind::LeatherLeggings,
        ItemKind::LeatherBoots,
        ItemKind::CopperHelmet,
        ItemKind::CopperChestplate,
        ItemKind::CopperLeggings,
        ItemKind::CopperBoots,
        ItemKind::ChainmailHelmet,
        ItemKind::ChainmailChestplate,
        ItemKind::ChainmailLeggings,
        ItemKind::ChainmailBoots,
        ItemKind::IronHelmet,
        ItemKind::IronChestplate,
        ItemKind::IronLeggings,
        ItemKind::IronBoots,
        ItemKind::DiamondHelmet,
        ItemKind::DiamondChestplate,
        ItemKind::DiamondLeggings,
        ItemKind::DiamondBoots,
        ItemKind::GoldenHelmet,
        ItemKind::GoldenChestplate,
        ItemKind::GoldenLeggings,
        ItemKind::GoldenBoots,
        ItemKind::NetheriteHelmet,
        ItemKind::NetheriteChestplate,
        ItemKind::NetheriteLeggings,
        ItemKind::NetheriteBoots,
        ItemKind::FishingRod,
        ItemKind::Shears,
        ItemKind::Mace,
        ItemKind::Shield,
        ItemKind::WoodenSpear,
        ItemKind::StoneSpear,
        ItemKind::CopperSpear,
        ItemKind::IronSpear,
        ItemKind::GoldenSpear,
        ItemKind::DiamondSpear,
        ItemKind::NetheriteSpear,
        ItemKind::Trident,
        ItemKind::Crossbow,
        ItemKind::Brush,
    ])
});
pub static ENCHANTABLE_EQUIPPABLE: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CarvedPumpkin,
        ItemKind::Elytra,
        ItemKind::TurtleHelmet,
        ItemKind::LeatherHelmet,
        ItemKind::LeatherChestplate,
        ItemKind::LeatherLeggings,
        ItemKind::LeatherBoots,
        ItemKind::CopperHelmet,
        ItemKind::CopperChestplate,
        ItemKind::CopperLeggings,
        ItemKind::CopperBoots,
        ItemKind::ChainmailHelmet,
        ItemKind::ChainmailChestplate,
        ItemKind::ChainmailLeggings,
        ItemKind::ChainmailBoots,
        ItemKind::IronHelmet,
        ItemKind::IronChestplate,
        ItemKind::IronLeggings,
        ItemKind::IronBoots,
        ItemKind::DiamondHelmet,
        ItemKind::DiamondChestplate,
        ItemKind::DiamondLeggings,
        ItemKind::DiamondBoots,
        ItemKind::GoldenHelmet,
        ItemKind::GoldenChestplate,
        ItemKind::GoldenLeggings,
        ItemKind::GoldenBoots,
        ItemKind::NetheriteHelmet,
        ItemKind::NetheriteChestplate,
        ItemKind::NetheriteLeggings,
        ItemKind::NetheriteBoots,
        ItemKind::SkeletonSkull,
        ItemKind::WitherSkeletonSkull,
        ItemKind::PlayerHead,
        ItemKind::ZombieHead,
        ItemKind::CreeperHead,
        ItemKind::DragonHead,
        ItemKind::PiglinHead,
    ])
});
pub static ENCHANTABLE_FIRE_ASPECT: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenSword,
        ItemKind::CopperSword,
        ItemKind::StoneSword,
        ItemKind::GoldenSword,
        ItemKind::IronSword,
        ItemKind::DiamondSword,
        ItemKind::NetheriteSword,
        ItemKind::Mace,
        ItemKind::WoodenSpear,
        ItemKind::StoneSpear,
        ItemKind::CopperSpear,
        ItemKind::IronSpear,
        ItemKind::GoldenSpear,
        ItemKind::DiamondSpear,
        ItemKind::NetheriteSpear,
    ])
});
pub static ENCHANTABLE_FISHING: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::FishingRod]));
pub static ENCHANTABLE_FOOT_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::LeatherBoots,
        ItemKind::CopperBoots,
        ItemKind::ChainmailBoots,
        ItemKind::IronBoots,
        ItemKind::DiamondBoots,
        ItemKind::GoldenBoots,
        ItemKind::NetheriteBoots,
    ])
});
pub static ENCHANTABLE_HEAD_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::TurtleHelmet,
        ItemKind::LeatherHelmet,
        ItemKind::CopperHelmet,
        ItemKind::ChainmailHelmet,
        ItemKind::IronHelmet,
        ItemKind::DiamondHelmet,
        ItemKind::GoldenHelmet,
        ItemKind::NetheriteHelmet,
    ])
});
pub static ENCHANTABLE_LEG_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::LeatherLeggings,
        ItemKind::CopperLeggings,
        ItemKind::ChainmailLeggings,
        ItemKind::IronLeggings,
        ItemKind::DiamondLeggings,
        ItemKind::GoldenLeggings,
        ItemKind::NetheriteLeggings,
    ])
});
pub static ENCHANTABLE_LUNGE: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenSpear,
        ItemKind::StoneSpear,
        ItemKind::CopperSpear,
        ItemKind::IronSpear,
        ItemKind::GoldenSpear,
        ItemKind::DiamondSpear,
        ItemKind::NetheriteSpear,
    ])
});
pub static ENCHANTABLE_MACE: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Mace]));
pub static ENCHANTABLE_MELEE_WEAPON: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenSword,
        ItemKind::CopperSword,
        ItemKind::StoneSword,
        ItemKind::GoldenSword,
        ItemKind::IronSword,
        ItemKind::DiamondSword,
        ItemKind::NetheriteSword,
        ItemKind::WoodenSpear,
        ItemKind::StoneSpear,
        ItemKind::CopperSpear,
        ItemKind::IronSpear,
        ItemKind::GoldenSpear,
        ItemKind::DiamondSpear,
        ItemKind::NetheriteSpear,
    ])
});
pub static ENCHANTABLE_MINING: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenShovel,
        ItemKind::WoodenPickaxe,
        ItemKind::WoodenAxe,
        ItemKind::WoodenHoe,
        ItemKind::CopperShovel,
        ItemKind::CopperPickaxe,
        ItemKind::CopperAxe,
        ItemKind::CopperHoe,
        ItemKind::StoneShovel,
        ItemKind::StonePickaxe,
        ItemKind::StoneAxe,
        ItemKind::StoneHoe,
        ItemKind::GoldenShovel,
        ItemKind::GoldenPickaxe,
        ItemKind::GoldenAxe,
        ItemKind::GoldenHoe,
        ItemKind::IronShovel,
        ItemKind::IronPickaxe,
        ItemKind::IronAxe,
        ItemKind::IronHoe,
        ItemKind::DiamondShovel,
        ItemKind::DiamondPickaxe,
        ItemKind::DiamondAxe,
        ItemKind::DiamondHoe,
        ItemKind::NetheriteShovel,
        ItemKind::NetheritePickaxe,
        ItemKind::NetheriteAxe,
        ItemKind::NetheriteHoe,
        ItemKind::Shears,
    ])
});
pub static ENCHANTABLE_MINING_LOOT: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenShovel,
        ItemKind::WoodenPickaxe,
        ItemKind::WoodenAxe,
        ItemKind::WoodenHoe,
        ItemKind::CopperShovel,
        ItemKind::CopperPickaxe,
        ItemKind::CopperAxe,
        ItemKind::CopperHoe,
        ItemKind::StoneShovel,
        ItemKind::StonePickaxe,
        ItemKind::StoneAxe,
        ItemKind::StoneHoe,
        ItemKind::GoldenShovel,
        ItemKind::GoldenPickaxe,
        ItemKind::GoldenAxe,
        ItemKind::GoldenHoe,
        ItemKind::IronShovel,
        ItemKind::IronPickaxe,
        ItemKind::IronAxe,
        ItemKind::IronHoe,
        ItemKind::DiamondShovel,
        ItemKind::DiamondPickaxe,
        ItemKind::DiamondAxe,
        ItemKind::DiamondHoe,
        ItemKind::NetheriteShovel,
        ItemKind::NetheritePickaxe,
        ItemKind::NetheriteAxe,
        ItemKind::NetheriteHoe,
    ])
});
pub static ENCHANTABLE_SHARP_WEAPON: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenSword,
        ItemKind::WoodenAxe,
        ItemKind::CopperSword,
        ItemKind::CopperAxe,
        ItemKind::StoneSword,
        ItemKind::StoneAxe,
        ItemKind::GoldenSword,
        ItemKind::GoldenAxe,
        ItemKind::IronSword,
        ItemKind::IronAxe,
        ItemKind::DiamondSword,
        ItemKind::DiamondAxe,
        ItemKind::NetheriteSword,
        ItemKind::NetheriteAxe,
        ItemKind::WoodenSpear,
        ItemKind::StoneSpear,
        ItemKind::CopperSpear,
        ItemKind::IronSpear,
        ItemKind::GoldenSpear,
        ItemKind::DiamondSpear,
        ItemKind::NetheriteSpear,
    ])
});
pub static ENCHANTABLE_SWEEPING: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenSword,
        ItemKind::CopperSword,
        ItemKind::StoneSword,
        ItemKind::GoldenSword,
        ItemKind::IronSword,
        ItemKind::DiamondSword,
        ItemKind::NetheriteSword,
    ])
});
pub static ENCHANTABLE_TRIDENT: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Trident]));
pub static ENCHANTABLE_VANISHING: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CarvedPumpkin,
        ItemKind::CarrotOnAStick,
        ItemKind::WarpedFungusOnAStick,
        ItemKind::Elytra,
        ItemKind::TurtleHelmet,
        ItemKind::FlintAndSteel,
        ItemKind::Bow,
        ItemKind::WoodenSword,
        ItemKind::WoodenShovel,
        ItemKind::WoodenPickaxe,
        ItemKind::WoodenAxe,
        ItemKind::WoodenHoe,
        ItemKind::CopperSword,
        ItemKind::CopperShovel,
        ItemKind::CopperPickaxe,
        ItemKind::CopperAxe,
        ItemKind::CopperHoe,
        ItemKind::StoneSword,
        ItemKind::StoneShovel,
        ItemKind::StonePickaxe,
        ItemKind::StoneAxe,
        ItemKind::StoneHoe,
        ItemKind::GoldenSword,
        ItemKind::GoldenShovel,
        ItemKind::GoldenPickaxe,
        ItemKind::GoldenAxe,
        ItemKind::GoldenHoe,
        ItemKind::IronSword,
        ItemKind::IronShovel,
        ItemKind::IronPickaxe,
        ItemKind::IronAxe,
        ItemKind::IronHoe,
        ItemKind::DiamondSword,
        ItemKind::DiamondShovel,
        ItemKind::DiamondPickaxe,
        ItemKind::DiamondAxe,
        ItemKind::DiamondHoe,
        ItemKind::NetheriteSword,
        ItemKind::NetheriteShovel,
        ItemKind::NetheritePickaxe,
        ItemKind::NetheriteAxe,
        ItemKind::NetheriteHoe,
        ItemKind::LeatherHelmet,
        ItemKind::LeatherChestplate,
        ItemKind::LeatherLeggings,
        ItemKind::LeatherBoots,
        ItemKind::CopperHelmet,
        ItemKind::CopperChestplate,
        ItemKind::CopperLeggings,
        ItemKind::CopperBoots,
        ItemKind::ChainmailHelmet,
        ItemKind::ChainmailChestplate,
        ItemKind::ChainmailLeggings,
        ItemKind::ChainmailBoots,
        ItemKind::IronHelmet,
        ItemKind::IronChestplate,
        ItemKind::IronLeggings,
        ItemKind::IronBoots,
        ItemKind::DiamondHelmet,
        ItemKind::DiamondChestplate,
        ItemKind::DiamondLeggings,
        ItemKind::DiamondBoots,
        ItemKind::GoldenHelmet,
        ItemKind::GoldenChestplate,
        ItemKind::GoldenLeggings,
        ItemKind::GoldenBoots,
        ItemKind::NetheriteHelmet,
        ItemKind::NetheriteChestplate,
        ItemKind::NetheriteLeggings,
        ItemKind::NetheriteBoots,
        ItemKind::Compass,
        ItemKind::FishingRod,
        ItemKind::Shears,
        ItemKind::Mace,
        ItemKind::SkeletonSkull,
        ItemKind::WitherSkeletonSkull,
        ItemKind::PlayerHead,
        ItemKind::ZombieHead,
        ItemKind::CreeperHead,
        ItemKind::DragonHead,
        ItemKind::PiglinHead,
        ItemKind::Shield,
        ItemKind::WoodenSpear,
        ItemKind::StoneSpear,
        ItemKind::CopperSpear,
        ItemKind::IronSpear,
        ItemKind::GoldenSpear,
        ItemKind::DiamondSpear,
        ItemKind::NetheriteSpear,
        ItemKind::Trident,
        ItemKind::Crossbow,
        ItemKind::Brush,
    ])
});
pub static ENCHANTABLE_WEAPON: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenSword,
        ItemKind::WoodenAxe,
        ItemKind::CopperSword,
        ItemKind::CopperAxe,
        ItemKind::StoneSword,
        ItemKind::StoneAxe,
        ItemKind::GoldenSword,
        ItemKind::GoldenAxe,
        ItemKind::IronSword,
        ItemKind::IronAxe,
        ItemKind::DiamondSword,
        ItemKind::DiamondAxe,
        ItemKind::NetheriteSword,
        ItemKind::NetheriteAxe,
        ItemKind::Mace,
        ItemKind::WoodenSpear,
        ItemKind::StoneSpear,
        ItemKind::CopperSpear,
        ItemKind::IronSpear,
        ItemKind::GoldenSpear,
        ItemKind::DiamondSpear,
        ItemKind::NetheriteSpear,
    ])
});
pub static FENCE_GATES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakFenceGate,
        ItemKind::SpruceFenceGate,
        ItemKind::BirchFenceGate,
        ItemKind::JungleFenceGate,
        ItemKind::AcaciaFenceGate,
        ItemKind::CherryFenceGate,
        ItemKind::DarkOakFenceGate,
        ItemKind::PaleOakFenceGate,
        ItemKind::MangroveFenceGate,
        ItemKind::BambooFenceGate,
        ItemKind::CrimsonFenceGate,
        ItemKind::WarpedFenceGate,
    ])
});
pub static FENCES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakFence,
        ItemKind::SpruceFence,
        ItemKind::BirchFence,
        ItemKind::JungleFence,
        ItemKind::AcaciaFence,
        ItemKind::CherryFence,
        ItemKind::DarkOakFence,
        ItemKind::PaleOakFence,
        ItemKind::MangroveFence,
        ItemKind::BambooFence,
        ItemKind::CrimsonFence,
        ItemKind::WarpedFence,
        ItemKind::NetherBrickFence,
    ])
});
pub static FISHES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Cod,
        ItemKind::Salmon,
        ItemKind::TropicalFish,
        ItemKind::Pufferfish,
        ItemKind::CookedCod,
        ItemKind::CookedSalmon,
    ])
});
pub static FLOWERS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::MangrovePropagule,
        ItemKind::CherryLeaves,
        ItemKind::FloweringAzaleaLeaves,
        ItemKind::FloweringAzalea,
        ItemKind::Dandelion,
        ItemKind::OpenEyeblossom,
        ItemKind::ClosedEyeblossom,
        ItemKind::Poppy,
        ItemKind::BlueOrchid,
        ItemKind::Allium,
        ItemKind::AzureBluet,
        ItemKind::RedTulip,
        ItemKind::OrangeTulip,
        ItemKind::WhiteTulip,
        ItemKind::PinkTulip,
        ItemKind::OxeyeDaisy,
        ItemKind::Cornflower,
        ItemKind::LilyOfTheValley,
        ItemKind::WitherRose,
        ItemKind::Torchflower,
        ItemKind::PitcherPlant,
        ItemKind::SporeBlossom,
        ItemKind::PinkPetals,
        ItemKind::Wildflowers,
        ItemKind::ChorusFlower,
        ItemKind::CactusFlower,
        ItemKind::Sunflower,
        ItemKind::Lilac,
        ItemKind::RoseBush,
        ItemKind::Peony,
    ])
});
pub static FOOT_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::LeatherBoots,
        ItemKind::CopperBoots,
        ItemKind::ChainmailBoots,
        ItemKind::IronBoots,
        ItemKind::DiamondBoots,
        ItemKind::GoldenBoots,
        ItemKind::NetheriteBoots,
    ])
});
pub static FOX_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::SweetBerries, ItemKind::GlowBerries]));
pub static FREEZE_IMMUNE_WEARABLES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::LeatherHelmet,
        ItemKind::LeatherChestplate,
        ItemKind::LeatherLeggings,
        ItemKind::LeatherBoots,
        ItemKind::LeatherHorseArmor,
    ])
});
pub static FROG_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::SlimeBall]));
pub static FURNACE_MINECART_FUEL: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Coal, ItemKind::Charcoal]));
pub static GAZE_DISGUISE_EQUIPMENT: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::CarvedPumpkin]));
pub static GOAT_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Wheat]));
pub static GOLD_ORES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::GoldOre,
        ItemKind::DeepslateGoldOre,
        ItemKind::NetherGoldOre,
    ])
});
pub static GOLD_TOOL_MATERIALS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::GoldIngot]));
pub static HANGING_SIGNS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakHangingSign,
        ItemKind::SpruceHangingSign,
        ItemKind::BirchHangingSign,
        ItemKind::JungleHangingSign,
        ItemKind::AcaciaHangingSign,
        ItemKind::CherryHangingSign,
        ItemKind::DarkOakHangingSign,
        ItemKind::PaleOakHangingSign,
        ItemKind::MangroveHangingSign,
        ItemKind::BambooHangingSign,
        ItemKind::CrimsonHangingSign,
        ItemKind::WarpedHangingSign,
    ])
});
pub static HAPPY_GHAST_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Snowball]));
pub static HAPPY_GHAST_TEMPT_ITEMS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WhiteHarness,
        ItemKind::OrangeHarness,
        ItemKind::MagentaHarness,
        ItemKind::LightBlueHarness,
        ItemKind::YellowHarness,
        ItemKind::LimeHarness,
        ItemKind::PinkHarness,
        ItemKind::GrayHarness,
        ItemKind::LightGrayHarness,
        ItemKind::CyanHarness,
        ItemKind::PurpleHarness,
        ItemKind::BlueHarness,
        ItemKind::BrownHarness,
        ItemKind::GreenHarness,
        ItemKind::RedHarness,
        ItemKind::BlackHarness,
        ItemKind::Snowball,
    ])
});
pub static HARNESSES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WhiteHarness,
        ItemKind::OrangeHarness,
        ItemKind::MagentaHarness,
        ItemKind::LightBlueHarness,
        ItemKind::YellowHarness,
        ItemKind::LimeHarness,
        ItemKind::PinkHarness,
        ItemKind::GrayHarness,
        ItemKind::LightGrayHarness,
        ItemKind::CyanHarness,
        ItemKind::PurpleHarness,
        ItemKind::BlueHarness,
        ItemKind::BrownHarness,
        ItemKind::GreenHarness,
        ItemKind::RedHarness,
        ItemKind::BlackHarness,
    ])
});
pub static HEAD_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::TurtleHelmet,
        ItemKind::LeatherHelmet,
        ItemKind::CopperHelmet,
        ItemKind::ChainmailHelmet,
        ItemKind::IronHelmet,
        ItemKind::DiamondHelmet,
        ItemKind::GoldenHelmet,
        ItemKind::NetheriteHelmet,
    ])
});
pub static HOES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenHoe,
        ItemKind::CopperHoe,
        ItemKind::StoneHoe,
        ItemKind::GoldenHoe,
        ItemKind::IronHoe,
        ItemKind::DiamondHoe,
        ItemKind::NetheriteHoe,
    ])
});
pub static HOGLIN_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::CrimsonFungus]));
pub static HORSE_FOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::HayBlock,
        ItemKind::Apple,
        ItemKind::Wheat,
        ItemKind::GoldenApple,
        ItemKind::EnchantedGoldenApple,
        ItemKind::Sugar,
        ItemKind::Carrot,
        ItemKind::GoldenCarrot,
    ])
});
pub static HORSE_TEMPT_ITEMS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::GoldenApple,
        ItemKind::EnchantedGoldenApple,
        ItemKind::GoldenCarrot,
    ])
});
pub static IGNORED_BY_PIGLIN_BABIES: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Leather]));
pub static IRON_ORES: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::IronOre, ItemKind::DeepslateIronOre]));
pub static IRON_TOOL_MATERIALS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::IronIngot]));
pub static JUNGLE_LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::JungleLog,
        ItemKind::StrippedJungleLog,
        ItemKind::StrippedJungleWood,
        ItemKind::JungleWood,
    ])
});
pub static LANTERNS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Lantern,
        ItemKind::SoulLantern,
        ItemKind::CopperLantern,
        ItemKind::ExposedCopperLantern,
        ItemKind::WeatheredCopperLantern,
        ItemKind::OxidizedCopperLantern,
        ItemKind::WaxedCopperLantern,
        ItemKind::WaxedExposedCopperLantern,
        ItemKind::WaxedWeatheredCopperLantern,
        ItemKind::WaxedOxidizedCopperLantern,
    ])
});
pub static LAPIS_ORES: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::LapisOre, ItemKind::DeepslateLapisOre]));
pub static LEAVES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakLeaves,
        ItemKind::SpruceLeaves,
        ItemKind::BirchLeaves,
        ItemKind::JungleLeaves,
        ItemKind::AcaciaLeaves,
        ItemKind::CherryLeaves,
        ItemKind::DarkOakLeaves,
        ItemKind::PaleOakLeaves,
        ItemKind::MangroveLeaves,
        ItemKind::AzaleaLeaves,
        ItemKind::FloweringAzaleaLeaves,
    ])
});
pub static LECTERN_BOOKS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::WritableBook, ItemKind::WrittenBook]));
pub static LEG_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::LeatherLeggings,
        ItemKind::CopperLeggings,
        ItemKind::ChainmailLeggings,
        ItemKind::IronLeggings,
        ItemKind::DiamondLeggings,
        ItemKind::GoldenLeggings,
        ItemKind::NetheriteLeggings,
    ])
});
pub static LIGHTNING_RODS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::LightningRod,
        ItemKind::ExposedLightningRod,
        ItemKind::WeatheredLightningRod,
        ItemKind::OxidizedLightningRod,
        ItemKind::WaxedLightningRod,
        ItemKind::WaxedExposedLightningRod,
        ItemKind::WaxedWeatheredLightningRod,
        ItemKind::WaxedOxidizedLightningRod,
    ])
});
pub static LLAMA_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::HayBlock, ItemKind::Wheat]));
pub static LLAMA_TEMPT_ITEMS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::HayBlock]));
pub static LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakLog,
        ItemKind::SpruceLog,
        ItemKind::BirchLog,
        ItemKind::JungleLog,
        ItemKind::AcaciaLog,
        ItemKind::CherryLog,
        ItemKind::PaleOakLog,
        ItemKind::DarkOakLog,
        ItemKind::MangroveLog,
        ItemKind::CrimsonStem,
        ItemKind::WarpedStem,
        ItemKind::StrippedOakLog,
        ItemKind::StrippedSpruceLog,
        ItemKind::StrippedBirchLog,
        ItemKind::StrippedJungleLog,
        ItemKind::StrippedAcaciaLog,
        ItemKind::StrippedCherryLog,
        ItemKind::StrippedDarkOakLog,
        ItemKind::StrippedPaleOakLog,
        ItemKind::StrippedMangroveLog,
        ItemKind::StrippedCrimsonStem,
        ItemKind::StrippedWarpedStem,
        ItemKind::StrippedOakWood,
        ItemKind::StrippedSpruceWood,
        ItemKind::StrippedBirchWood,
        ItemKind::StrippedJungleWood,
        ItemKind::StrippedAcaciaWood,
        ItemKind::StrippedCherryWood,
        ItemKind::StrippedDarkOakWood,
        ItemKind::StrippedPaleOakWood,
        ItemKind::StrippedMangroveWood,
        ItemKind::StrippedCrimsonHyphae,
        ItemKind::StrippedWarpedHyphae,
        ItemKind::OakWood,
        ItemKind::SpruceWood,
        ItemKind::BirchWood,
        ItemKind::JungleWood,
        ItemKind::AcaciaWood,
        ItemKind::CherryWood,
        ItemKind::PaleOakWood,
        ItemKind::DarkOakWood,
        ItemKind::MangroveWood,
        ItemKind::CrimsonHyphae,
        ItemKind::WarpedHyphae,
    ])
});
pub static LOGS_THAT_BURN: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakLog,
        ItemKind::SpruceLog,
        ItemKind::BirchLog,
        ItemKind::JungleLog,
        ItemKind::AcaciaLog,
        ItemKind::CherryLog,
        ItemKind::PaleOakLog,
        ItemKind::DarkOakLog,
        ItemKind::MangroveLog,
        ItemKind::StrippedOakLog,
        ItemKind::StrippedSpruceLog,
        ItemKind::StrippedBirchLog,
        ItemKind::StrippedJungleLog,
        ItemKind::StrippedAcaciaLog,
        ItemKind::StrippedCherryLog,
        ItemKind::StrippedDarkOakLog,
        ItemKind::StrippedPaleOakLog,
        ItemKind::StrippedMangroveLog,
        ItemKind::StrippedOakWood,
        ItemKind::StrippedSpruceWood,
        ItemKind::StrippedBirchWood,
        ItemKind::StrippedJungleWood,
        ItemKind::StrippedAcaciaWood,
        ItemKind::StrippedCherryWood,
        ItemKind::StrippedDarkOakWood,
        ItemKind::StrippedPaleOakWood,
        ItemKind::StrippedMangroveWood,
        ItemKind::OakWood,
        ItemKind::SpruceWood,
        ItemKind::BirchWood,
        ItemKind::JungleWood,
        ItemKind::AcaciaWood,
        ItemKind::CherryWood,
        ItemKind::PaleOakWood,
        ItemKind::DarkOakWood,
        ItemKind::MangroveWood,
    ])
});
pub static MANGROVE_LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::MangroveLog,
        ItemKind::StrippedMangroveLog,
        ItemKind::StrippedMangroveWood,
        ItemKind::MangroveWood,
    ])
});
pub static MAP_INVISIBILITY_EQUIPMENT: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::CarvedPumpkin]));
pub static MEAT: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Porkchop,
        ItemKind::CookedPorkchop,
        ItemKind::Beef,
        ItemKind::CookedBeef,
        ItemKind::Chicken,
        ItemKind::CookedChicken,
        ItemKind::RottenFlesh,
        ItemKind::Rabbit,
        ItemKind::CookedRabbit,
        ItemKind::Mutton,
        ItemKind::CookedMutton,
    ])
});
pub static NAUTILUS_BUCKET_FOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::PufferfishBucket,
        ItemKind::SalmonBucket,
        ItemKind::CodBucket,
        ItemKind::TropicalFishBucket,
    ])
});
pub static NAUTILUS_FOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::PufferfishBucket,
        ItemKind::SalmonBucket,
        ItemKind::CodBucket,
        ItemKind::TropicalFishBucket,
        ItemKind::Cod,
        ItemKind::Salmon,
        ItemKind::TropicalFish,
        ItemKind::Pufferfish,
        ItemKind::CookedCod,
        ItemKind::CookedSalmon,
    ])
});
pub static NAUTILUS_TAMING_ITEMS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::PufferfishBucket, ItemKind::Pufferfish]));
pub static NETHERITE_TOOL_MATERIALS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::NetheriteIngot]));
pub static NON_FLAMMABLE_WOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CrimsonPlanks,
        ItemKind::WarpedPlanks,
        ItemKind::CrimsonStem,
        ItemKind::WarpedStem,
        ItemKind::StrippedCrimsonStem,
        ItemKind::StrippedWarpedStem,
        ItemKind::StrippedCrimsonHyphae,
        ItemKind::StrippedWarpedHyphae,
        ItemKind::CrimsonHyphae,
        ItemKind::WarpedHyphae,
        ItemKind::CrimsonSlab,
        ItemKind::WarpedSlab,
        ItemKind::CrimsonShelf,
        ItemKind::WarpedShelf,
        ItemKind::CrimsonFence,
        ItemKind::WarpedFence,
        ItemKind::CrimsonStairs,
        ItemKind::WarpedStairs,
        ItemKind::CrimsonButton,
        ItemKind::WarpedButton,
        ItemKind::CrimsonPressurePlate,
        ItemKind::WarpedPressurePlate,
        ItemKind::CrimsonDoor,
        ItemKind::WarpedDoor,
        ItemKind::CrimsonTrapdoor,
        ItemKind::WarpedTrapdoor,
        ItemKind::CrimsonFenceGate,
        ItemKind::WarpedFenceGate,
        ItemKind::CrimsonSign,
        ItemKind::WarpedSign,
        ItemKind::CrimsonHangingSign,
        ItemKind::WarpedHangingSign,
    ])
});
pub static NOTEBLOCK_TOP_INSTRUMENTS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::SkeletonSkull,
        ItemKind::WitherSkeletonSkull,
        ItemKind::PlayerHead,
        ItemKind::ZombieHead,
        ItemKind::CreeperHead,
        ItemKind::DragonHead,
        ItemKind::PiglinHead,
    ])
});
pub static OAK_LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakLog,
        ItemKind::StrippedOakLog,
        ItemKind::StrippedOakWood,
        ItemKind::OakWood,
    ])
});
pub static OCELOT_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Cod, ItemKind::Salmon]));
pub static PALE_OAK_LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::PaleOakLog,
        ItemKind::StrippedPaleOakLog,
        ItemKind::StrippedPaleOakWood,
        ItemKind::PaleOakWood,
    ])
});
pub static PANDA_EATS_FROM_GROUND: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Bamboo, ItemKind::Cake]));
pub static PANDA_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Bamboo]));
pub static PARROT_FOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WheatSeeds,
        ItemKind::PumpkinSeeds,
        ItemKind::MelonSeeds,
        ItemKind::TorchflowerSeeds,
        ItemKind::PitcherPod,
        ItemKind::BeetrootSeeds,
    ])
});
pub static PARROT_POISONOUS_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Cookie]));
pub static PICKAXES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenPickaxe,
        ItemKind::CopperPickaxe,
        ItemKind::StonePickaxe,
        ItemKind::GoldenPickaxe,
        ItemKind::IronPickaxe,
        ItemKind::DiamondPickaxe,
        ItemKind::NetheritePickaxe,
    ])
});
pub static PIG_FOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![ItemKind::Carrot, ItemKind::Potato, ItemKind::Beetroot])
});
pub static PIGLIN_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Porkchop, ItemKind::CookedPorkchop]));
pub static PIGLIN_LOVED: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::GoldOre,
        ItemKind::DeepslateGoldOre,
        ItemKind::NetherGoldOre,
        ItemKind::RawGoldBlock,
        ItemKind::GoldBlock,
        ItemKind::LightWeightedPressurePlate,
        ItemKind::RawGold,
        ItemKind::GoldIngot,
        ItemKind::GoldenSword,
        ItemKind::GoldenShovel,
        ItemKind::GoldenPickaxe,
        ItemKind::GoldenAxe,
        ItemKind::GoldenHoe,
        ItemKind::GoldenHelmet,
        ItemKind::GoldenChestplate,
        ItemKind::GoldenLeggings,
        ItemKind::GoldenBoots,
        ItemKind::GoldenApple,
        ItemKind::EnchantedGoldenApple,
        ItemKind::Clock,
        ItemKind::GlisteringMelonSlice,
        ItemKind::GoldenCarrot,
        ItemKind::GoldenHorseArmor,
        ItemKind::GoldenSpear,
        ItemKind::GoldenNautilusArmor,
        ItemKind::Bell,
        ItemKind::GildedBlackstone,
    ])
});
pub static PIGLIN_PREFERRED_WEAPONS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::GoldenSpear, ItemKind::Crossbow]));
pub static PIGLIN_REPELLENTS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::SoulTorch,
        ItemKind::SoulLantern,
        ItemKind::SoulCampfire,
    ])
});
pub static PIGLIN_SAFE_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::GoldenHelmet,
        ItemKind::GoldenChestplate,
        ItemKind::GoldenLeggings,
        ItemKind::GoldenBoots,
    ])
});
pub static PILLAGER_PREFERRED_WEAPONS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Crossbow]));
pub static PLANKS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakPlanks,
        ItemKind::SprucePlanks,
        ItemKind::BirchPlanks,
        ItemKind::JunglePlanks,
        ItemKind::AcaciaPlanks,
        ItemKind::CherryPlanks,
        ItemKind::DarkOakPlanks,
        ItemKind::PaleOakPlanks,
        ItemKind::MangrovePlanks,
        ItemKind::BambooPlanks,
        ItemKind::CrimsonPlanks,
        ItemKind::WarpedPlanks,
    ])
});
pub static RABBIT_FOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Dandelion,
        ItemKind::Carrot,
        ItemKind::GoldenCarrot,
    ])
});
pub static RAILS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::PoweredRail,
        ItemKind::DetectorRail,
        ItemKind::Rail,
        ItemKind::ActivatorRail,
    ])
});
pub static REDSTONE_ORES: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::RedstoneOre, ItemKind::DeepslateRedstoneOre]));
pub static REPAIRS_CHAIN_ARMOR: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::IronIngot]));
pub static REPAIRS_COPPER_ARMOR: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::CopperIngot]));
pub static REPAIRS_DIAMOND_ARMOR: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Diamond]));
pub static REPAIRS_GOLD_ARMOR: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::GoldIngot]));
pub static REPAIRS_IRON_ARMOR: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::IronIngot]));
pub static REPAIRS_LEATHER_ARMOR: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Leather]));
pub static REPAIRS_NETHERITE_ARMOR: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::NetheriteIngot]));
pub static REPAIRS_TURTLE_HELMET: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::TurtleScute]));
pub static REPAIRS_WOLF_ARMOR: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::ArmadilloScute]));
pub static SAND: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Sand,
        ItemKind::SuspiciousSand,
        ItemKind::RedSand,
    ])
});
pub static SAPLINGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakSapling,
        ItemKind::SpruceSapling,
        ItemKind::BirchSapling,
        ItemKind::JungleSapling,
        ItemKind::AcaciaSapling,
        ItemKind::CherrySapling,
        ItemKind::DarkOakSapling,
        ItemKind::PaleOakSapling,
        ItemKind::MangrovePropagule,
        ItemKind::Azalea,
        ItemKind::FloweringAzalea,
    ])
});
pub static SHEARABLE_FROM_COPPER_GOLEM: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Poppy]));
pub static SHEEP_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Wheat]));
pub static SHOVELS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenShovel,
        ItemKind::CopperShovel,
        ItemKind::StoneShovel,
        ItemKind::GoldenShovel,
        ItemKind::IronShovel,
        ItemKind::DiamondShovel,
        ItemKind::NetheriteShovel,
    ])
});
pub static SHULKER_BOXES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::ShulkerBox,
        ItemKind::WhiteShulkerBox,
        ItemKind::OrangeShulkerBox,
        ItemKind::MagentaShulkerBox,
        ItemKind::LightBlueShulkerBox,
        ItemKind::YellowShulkerBox,
        ItemKind::LimeShulkerBox,
        ItemKind::PinkShulkerBox,
        ItemKind::GrayShulkerBox,
        ItemKind::LightGrayShulkerBox,
        ItemKind::CyanShulkerBox,
        ItemKind::PurpleShulkerBox,
        ItemKind::BlueShulkerBox,
        ItemKind::BrownShulkerBox,
        ItemKind::GreenShulkerBox,
        ItemKind::RedShulkerBox,
        ItemKind::BlackShulkerBox,
    ])
});
pub static SIGNS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakSign,
        ItemKind::SpruceSign,
        ItemKind::BirchSign,
        ItemKind::JungleSign,
        ItemKind::AcaciaSign,
        ItemKind::CherrySign,
        ItemKind::DarkOakSign,
        ItemKind::PaleOakSign,
        ItemKind::MangroveSign,
        ItemKind::BambooSign,
        ItemKind::CrimsonSign,
        ItemKind::WarpedSign,
    ])
});
pub static SKELETON_PREFERRED_WEAPONS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Bow]));
pub static SKULLS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::SkeletonSkull,
        ItemKind::WitherSkeletonSkull,
        ItemKind::PlayerHead,
        ItemKind::ZombieHead,
        ItemKind::CreeperHead,
        ItemKind::DragonHead,
        ItemKind::PiglinHead,
    ])
});
pub static SLABS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::TuffSlab,
        ItemKind::PolishedTuffSlab,
        ItemKind::TuffBrickSlab,
        ItemKind::CutCopperSlab,
        ItemKind::ExposedCutCopperSlab,
        ItemKind::WeatheredCutCopperSlab,
        ItemKind::OxidizedCutCopperSlab,
        ItemKind::WaxedCutCopperSlab,
        ItemKind::WaxedExposedCutCopperSlab,
        ItemKind::WaxedWeatheredCutCopperSlab,
        ItemKind::WaxedOxidizedCutCopperSlab,
        ItemKind::OakSlab,
        ItemKind::SpruceSlab,
        ItemKind::BirchSlab,
        ItemKind::JungleSlab,
        ItemKind::AcaciaSlab,
        ItemKind::CherrySlab,
        ItemKind::DarkOakSlab,
        ItemKind::PaleOakSlab,
        ItemKind::MangroveSlab,
        ItemKind::BambooSlab,
        ItemKind::BambooMosaicSlab,
        ItemKind::CrimsonSlab,
        ItemKind::WarpedSlab,
        ItemKind::StoneSlab,
        ItemKind::SmoothStoneSlab,
        ItemKind::SandstoneSlab,
        ItemKind::CutSandstoneSlab,
        ItemKind::PetrifiedOakSlab,
        ItemKind::CobblestoneSlab,
        ItemKind::BrickSlab,
        ItemKind::StoneBrickSlab,
        ItemKind::MudBrickSlab,
        ItemKind::NetherBrickSlab,
        ItemKind::QuartzSlab,
        ItemKind::RedSandstoneSlab,
        ItemKind::CutRedSandstoneSlab,
        ItemKind::PurpurSlab,
        ItemKind::PrismarineSlab,
        ItemKind::PrismarineBrickSlab,
        ItemKind::DarkPrismarineSlab,
        ItemKind::ResinBrickSlab,
        ItemKind::PolishedGraniteSlab,
        ItemKind::SmoothRedSandstoneSlab,
        ItemKind::MossyStoneBrickSlab,
        ItemKind::PolishedDioriteSlab,
        ItemKind::MossyCobblestoneSlab,
        ItemKind::EndStoneBrickSlab,
        ItemKind::SmoothSandstoneSlab,
        ItemKind::SmoothQuartzSlab,
        ItemKind::GraniteSlab,
        ItemKind::AndesiteSlab,
        ItemKind::RedNetherBrickSlab,
        ItemKind::PolishedAndesiteSlab,
        ItemKind::DioriteSlab,
        ItemKind::CobbledDeepslateSlab,
        ItemKind::PolishedDeepslateSlab,
        ItemKind::DeepslateBrickSlab,
        ItemKind::DeepslateTileSlab,
        ItemKind::BlackstoneSlab,
        ItemKind::PolishedBlackstoneSlab,
        ItemKind::PolishedBlackstoneBrickSlab,
    ])
});
pub static SMALL_FLOWERS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Dandelion,
        ItemKind::OpenEyeblossom,
        ItemKind::ClosedEyeblossom,
        ItemKind::Poppy,
        ItemKind::BlueOrchid,
        ItemKind::Allium,
        ItemKind::AzureBluet,
        ItemKind::RedTulip,
        ItemKind::OrangeTulip,
        ItemKind::WhiteTulip,
        ItemKind::PinkTulip,
        ItemKind::OxeyeDaisy,
        ItemKind::Cornflower,
        ItemKind::LilyOfTheValley,
        ItemKind::WitherRose,
        ItemKind::Torchflower,
    ])
});
pub static SMELTS_TO_GLASS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Sand, ItemKind::RedSand]));
pub static SNIFFER_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::TorchflowerSeeds]));
pub static SOUL_FIRE_BASE_BLOCKS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::SoulSand, ItemKind::SoulSoil]));
pub static SPEARS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenSpear,
        ItemKind::StoneSpear,
        ItemKind::CopperSpear,
        ItemKind::IronSpear,
        ItemKind::GoldenSpear,
        ItemKind::DiamondSpear,
        ItemKind::NetheriteSpear,
    ])
});
pub static SPRUCE_LOGS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::SpruceLog,
        ItemKind::StrippedSpruceLog,
        ItemKind::StrippedSpruceWood,
        ItemKind::SpruceWood,
    ])
});
pub static STAIRS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::TuffStairs,
        ItemKind::PolishedTuffStairs,
        ItemKind::TuffBrickStairs,
        ItemKind::CutCopperStairs,
        ItemKind::ExposedCutCopperStairs,
        ItemKind::WeatheredCutCopperStairs,
        ItemKind::OxidizedCutCopperStairs,
        ItemKind::WaxedCutCopperStairs,
        ItemKind::WaxedExposedCutCopperStairs,
        ItemKind::WaxedWeatheredCutCopperStairs,
        ItemKind::WaxedOxidizedCutCopperStairs,
        ItemKind::PurpurStairs,
        ItemKind::CobblestoneStairs,
        ItemKind::ResinBrickStairs,
        ItemKind::BrickStairs,
        ItemKind::StoneBrickStairs,
        ItemKind::MudBrickStairs,
        ItemKind::NetherBrickStairs,
        ItemKind::SandstoneStairs,
        ItemKind::OakStairs,
        ItemKind::SpruceStairs,
        ItemKind::BirchStairs,
        ItemKind::JungleStairs,
        ItemKind::AcaciaStairs,
        ItemKind::CherryStairs,
        ItemKind::DarkOakStairs,
        ItemKind::PaleOakStairs,
        ItemKind::MangroveStairs,
        ItemKind::BambooStairs,
        ItemKind::BambooMosaicStairs,
        ItemKind::CrimsonStairs,
        ItemKind::WarpedStairs,
        ItemKind::QuartzStairs,
        ItemKind::PrismarineStairs,
        ItemKind::PrismarineBrickStairs,
        ItemKind::DarkPrismarineStairs,
        ItemKind::RedSandstoneStairs,
        ItemKind::PolishedGraniteStairs,
        ItemKind::SmoothRedSandstoneStairs,
        ItemKind::MossyStoneBrickStairs,
        ItemKind::PolishedDioriteStairs,
        ItemKind::MossyCobblestoneStairs,
        ItemKind::EndStoneBrickStairs,
        ItemKind::StoneStairs,
        ItemKind::SmoothSandstoneStairs,
        ItemKind::SmoothQuartzStairs,
        ItemKind::GraniteStairs,
        ItemKind::AndesiteStairs,
        ItemKind::RedNetherBrickStairs,
        ItemKind::PolishedAndesiteStairs,
        ItemKind::DioriteStairs,
        ItemKind::CobbledDeepslateStairs,
        ItemKind::PolishedDeepslateStairs,
        ItemKind::DeepslateBrickStairs,
        ItemKind::DeepslateTileStairs,
        ItemKind::BlackstoneStairs,
        ItemKind::PolishedBlackstoneStairs,
        ItemKind::PolishedBlackstoneBrickStairs,
    ])
});
pub static STONE_BRICKS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::StoneBricks,
        ItemKind::MossyStoneBricks,
        ItemKind::CrackedStoneBricks,
        ItemKind::ChiseledStoneBricks,
    ])
});
pub static STONE_BUTTONS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::StoneButton,
        ItemKind::PolishedBlackstoneButton,
    ])
});
pub static STONE_CRAFTING_MATERIALS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CobbledDeepslate,
        ItemKind::Cobblestone,
        ItemKind::Blackstone,
    ])
});
pub static STONE_TOOL_MATERIALS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::CobbledDeepslate,
        ItemKind::Cobblestone,
        ItemKind::Blackstone,
    ])
});
pub static STRIDER_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::WarpedFungus]));
pub static STRIDER_TEMPT_ITEMS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![ItemKind::WarpedFungus, ItemKind::WarpedFungusOnAStick])
});
pub static SWORDS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WoodenSword,
        ItemKind::CopperSword,
        ItemKind::StoneSword,
        ItemKind::GoldenSword,
        ItemKind::IronSword,
        ItemKind::DiamondSword,
        ItemKind::NetheriteSword,
    ])
});
pub static TERRACOTTA: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WhiteTerracotta,
        ItemKind::OrangeTerracotta,
        ItemKind::MagentaTerracotta,
        ItemKind::LightBlueTerracotta,
        ItemKind::YellowTerracotta,
        ItemKind::LimeTerracotta,
        ItemKind::PinkTerracotta,
        ItemKind::GrayTerracotta,
        ItemKind::LightGrayTerracotta,
        ItemKind::CyanTerracotta,
        ItemKind::PurpleTerracotta,
        ItemKind::BlueTerracotta,
        ItemKind::BrownTerracotta,
        ItemKind::GreenTerracotta,
        ItemKind::RedTerracotta,
        ItemKind::BlackTerracotta,
        ItemKind::Terracotta,
    ])
});
pub static TRAPDOORS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::IronTrapdoor,
        ItemKind::OakTrapdoor,
        ItemKind::SpruceTrapdoor,
        ItemKind::BirchTrapdoor,
        ItemKind::JungleTrapdoor,
        ItemKind::AcaciaTrapdoor,
        ItemKind::CherryTrapdoor,
        ItemKind::DarkOakTrapdoor,
        ItemKind::PaleOakTrapdoor,
        ItemKind::MangroveTrapdoor,
        ItemKind::BambooTrapdoor,
        ItemKind::CrimsonTrapdoor,
        ItemKind::WarpedTrapdoor,
        ItemKind::CopperTrapdoor,
        ItemKind::ExposedCopperTrapdoor,
        ItemKind::WeatheredCopperTrapdoor,
        ItemKind::OxidizedCopperTrapdoor,
        ItemKind::WaxedCopperTrapdoor,
        ItemKind::WaxedExposedCopperTrapdoor,
        ItemKind::WaxedWeatheredCopperTrapdoor,
        ItemKind::WaxedOxidizedCopperTrapdoor,
    ])
});
pub static TRIM_MATERIALS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Redstone,
        ItemKind::Diamond,
        ItemKind::Emerald,
        ItemKind::LapisLazuli,
        ItemKind::Quartz,
        ItemKind::AmethystShard,
        ItemKind::IronIngot,
        ItemKind::CopperIngot,
        ItemKind::GoldIngot,
        ItemKind::NetheriteIngot,
        ItemKind::ResinBrick,
    ])
});
pub static TRIMMABLE_ARMOR: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::TurtleHelmet,
        ItemKind::LeatherHelmet,
        ItemKind::LeatherChestplate,
        ItemKind::LeatherLeggings,
        ItemKind::LeatherBoots,
        ItemKind::CopperHelmet,
        ItemKind::CopperChestplate,
        ItemKind::CopperLeggings,
        ItemKind::CopperBoots,
        ItemKind::ChainmailHelmet,
        ItemKind::ChainmailChestplate,
        ItemKind::ChainmailLeggings,
        ItemKind::ChainmailBoots,
        ItemKind::IronHelmet,
        ItemKind::IronChestplate,
        ItemKind::IronLeggings,
        ItemKind::IronBoots,
        ItemKind::DiamondHelmet,
        ItemKind::DiamondChestplate,
        ItemKind::DiamondLeggings,
        ItemKind::DiamondBoots,
        ItemKind::GoldenHelmet,
        ItemKind::GoldenChestplate,
        ItemKind::GoldenLeggings,
        ItemKind::GoldenBoots,
        ItemKind::NetheriteHelmet,
        ItemKind::NetheriteChestplate,
        ItemKind::NetheriteLeggings,
        ItemKind::NetheriteBoots,
    ])
});
pub static TURTLE_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Seagrass]));
pub static VILLAGER_PICKS_UP: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WheatSeeds,
        ItemKind::Wheat,
        ItemKind::Bread,
        ItemKind::Carrot,
        ItemKind::Potato,
        ItemKind::TorchflowerSeeds,
        ItemKind::PitcherPod,
        ItemKind::Beetroot,
        ItemKind::BeetrootSeeds,
    ])
});
pub static VILLAGER_PLANTABLE_SEEDS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WheatSeeds,
        ItemKind::Carrot,
        ItemKind::Potato,
        ItemKind::TorchflowerSeeds,
        ItemKind::PitcherPod,
        ItemKind::BeetrootSeeds,
    ])
});
pub static WALLS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::TuffWall,
        ItemKind::PolishedTuffWall,
        ItemKind::TuffBrickWall,
        ItemKind::ResinBrickWall,
        ItemKind::CobblestoneWall,
        ItemKind::MossyCobblestoneWall,
        ItemKind::BrickWall,
        ItemKind::PrismarineWall,
        ItemKind::RedSandstoneWall,
        ItemKind::MossyStoneBrickWall,
        ItemKind::GraniteWall,
        ItemKind::StoneBrickWall,
        ItemKind::MudBrickWall,
        ItemKind::NetherBrickWall,
        ItemKind::AndesiteWall,
        ItemKind::RedNetherBrickWall,
        ItemKind::SandstoneWall,
        ItemKind::EndStoneBrickWall,
        ItemKind::DioriteWall,
        ItemKind::BlackstoneWall,
        ItemKind::PolishedBlackstoneWall,
        ItemKind::PolishedBlackstoneBrickWall,
        ItemKind::CobbledDeepslateWall,
        ItemKind::PolishedDeepslateWall,
        ItemKind::DeepslateBrickWall,
        ItemKind::DeepslateTileWall,
    ])
});
pub static WARPED_STEMS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WarpedStem,
        ItemKind::StrippedWarpedStem,
        ItemKind::StrippedWarpedHyphae,
        ItemKind::WarpedHyphae,
    ])
});
pub static WART_BLOCKS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::NetherWartBlock, ItemKind::WarpedWartBlock]));
pub static WITHER_SKELETON_DISLIKED_WEAPONS: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::Bow, ItemKind::Crossbow]));
pub static WOLF_FOOD: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::Porkchop,
        ItemKind::CookedPorkchop,
        ItemKind::Cod,
        ItemKind::Salmon,
        ItemKind::TropicalFish,
        ItemKind::Pufferfish,
        ItemKind::CookedCod,
        ItemKind::CookedSalmon,
        ItemKind::Beef,
        ItemKind::CookedBeef,
        ItemKind::Chicken,
        ItemKind::CookedChicken,
        ItemKind::RottenFlesh,
        ItemKind::Rabbit,
        ItemKind::CookedRabbit,
        ItemKind::RabbitStew,
        ItemKind::Mutton,
        ItemKind::CookedMutton,
    ])
});
pub static WOODEN_BUTTONS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakButton,
        ItemKind::SpruceButton,
        ItemKind::BirchButton,
        ItemKind::JungleButton,
        ItemKind::AcaciaButton,
        ItemKind::CherryButton,
        ItemKind::DarkOakButton,
        ItemKind::PaleOakButton,
        ItemKind::MangroveButton,
        ItemKind::BambooButton,
        ItemKind::CrimsonButton,
        ItemKind::WarpedButton,
    ])
});
pub static WOODEN_DOORS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakDoor,
        ItemKind::SpruceDoor,
        ItemKind::BirchDoor,
        ItemKind::JungleDoor,
        ItemKind::AcaciaDoor,
        ItemKind::CherryDoor,
        ItemKind::DarkOakDoor,
        ItemKind::PaleOakDoor,
        ItemKind::MangroveDoor,
        ItemKind::BambooDoor,
        ItemKind::CrimsonDoor,
        ItemKind::WarpedDoor,
    ])
});
pub static WOODEN_FENCES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakFence,
        ItemKind::SpruceFence,
        ItemKind::BirchFence,
        ItemKind::JungleFence,
        ItemKind::AcaciaFence,
        ItemKind::CherryFence,
        ItemKind::DarkOakFence,
        ItemKind::PaleOakFence,
        ItemKind::MangroveFence,
        ItemKind::BambooFence,
        ItemKind::CrimsonFence,
        ItemKind::WarpedFence,
    ])
});
pub static WOODEN_PRESSURE_PLATES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakPressurePlate,
        ItemKind::SprucePressurePlate,
        ItemKind::BirchPressurePlate,
        ItemKind::JunglePressurePlate,
        ItemKind::AcaciaPressurePlate,
        ItemKind::CherryPressurePlate,
        ItemKind::DarkOakPressurePlate,
        ItemKind::PaleOakPressurePlate,
        ItemKind::MangrovePressurePlate,
        ItemKind::BambooPressurePlate,
        ItemKind::CrimsonPressurePlate,
        ItemKind::WarpedPressurePlate,
    ])
});
pub static WOODEN_SHELVES: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::AcaciaShelf,
        ItemKind::BambooShelf,
        ItemKind::BirchShelf,
        ItemKind::CherryShelf,
        ItemKind::CrimsonShelf,
        ItemKind::DarkOakShelf,
        ItemKind::JungleShelf,
        ItemKind::MangroveShelf,
        ItemKind::OakShelf,
        ItemKind::PaleOakShelf,
        ItemKind::SpruceShelf,
        ItemKind::WarpedShelf,
    ])
});
pub static WOODEN_SLABS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakSlab,
        ItemKind::SpruceSlab,
        ItemKind::BirchSlab,
        ItemKind::JungleSlab,
        ItemKind::AcaciaSlab,
        ItemKind::CherrySlab,
        ItemKind::DarkOakSlab,
        ItemKind::PaleOakSlab,
        ItemKind::MangroveSlab,
        ItemKind::BambooSlab,
        ItemKind::CrimsonSlab,
        ItemKind::WarpedSlab,
    ])
});
pub static WOODEN_STAIRS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakStairs,
        ItemKind::SpruceStairs,
        ItemKind::BirchStairs,
        ItemKind::JungleStairs,
        ItemKind::AcaciaStairs,
        ItemKind::CherryStairs,
        ItemKind::DarkOakStairs,
        ItemKind::PaleOakStairs,
        ItemKind::MangroveStairs,
        ItemKind::BambooStairs,
        ItemKind::CrimsonStairs,
        ItemKind::WarpedStairs,
    ])
});
pub static WOODEN_TOOL_MATERIALS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakPlanks,
        ItemKind::SprucePlanks,
        ItemKind::BirchPlanks,
        ItemKind::JunglePlanks,
        ItemKind::AcaciaPlanks,
        ItemKind::CherryPlanks,
        ItemKind::DarkOakPlanks,
        ItemKind::PaleOakPlanks,
        ItemKind::MangrovePlanks,
        ItemKind::BambooPlanks,
        ItemKind::CrimsonPlanks,
        ItemKind::WarpedPlanks,
    ])
});
pub static WOODEN_TRAPDOORS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::OakTrapdoor,
        ItemKind::SpruceTrapdoor,
        ItemKind::BirchTrapdoor,
        ItemKind::JungleTrapdoor,
        ItemKind::AcaciaTrapdoor,
        ItemKind::CherryTrapdoor,
        ItemKind::DarkOakTrapdoor,
        ItemKind::PaleOakTrapdoor,
        ItemKind::MangroveTrapdoor,
        ItemKind::BambooTrapdoor,
        ItemKind::CrimsonTrapdoor,
        ItemKind::WarpedTrapdoor,
    ])
});
pub static WOOL: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WhiteWool,
        ItemKind::OrangeWool,
        ItemKind::MagentaWool,
        ItemKind::LightBlueWool,
        ItemKind::YellowWool,
        ItemKind::LimeWool,
        ItemKind::PinkWool,
        ItemKind::GrayWool,
        ItemKind::LightGrayWool,
        ItemKind::CyanWool,
        ItemKind::PurpleWool,
        ItemKind::BlueWool,
        ItemKind::BrownWool,
        ItemKind::GreenWool,
        ItemKind::RedWool,
        ItemKind::BlackWool,
    ])
});
pub static WOOL_CARPETS: LazyLock<RegistryTag<ItemKind>> = LazyLock::new(|| {
    RegistryTag::new(vec![
        ItemKind::WhiteCarpet,
        ItemKind::OrangeCarpet,
        ItemKind::MagentaCarpet,
        ItemKind::LightBlueCarpet,
        ItemKind::YellowCarpet,
        ItemKind::LimeCarpet,
        ItemKind::PinkCarpet,
        ItemKind::GrayCarpet,
        ItemKind::LightGrayCarpet,
        ItemKind::CyanCarpet,
        ItemKind::PurpleCarpet,
        ItemKind::BlueCarpet,
        ItemKind::BrownCarpet,
        ItemKind::GreenCarpet,
        ItemKind::RedCarpet,
        ItemKind::BlackCarpet,
    ])
});
pub static ZOMBIE_HORSE_FOOD: LazyLock<RegistryTag<ItemKind>> =
    LazyLock::new(|| RegistryTag::new(vec![ItemKind::RedMushroom]));
