// This file is @generated by `azalea-client/build.rs`.

mod change_dimension_to_nether_and_back;
mod client_disconnect;
mod close_open_container;
mod correct_movement;
mod correct_sneak_movement;
mod correct_sprint_sneak_movement;
mod despawn_entities_when_changing_dimension;
mod enchantments;
mod fast_login;
mod login_to_dimension_with_same_name;
mod mine_block_rollback;
mod mine_block_timing_hand;
mod mine_block_without_rollback;
mod move_and_despawn_entity;
mod move_despawned_entity;
mod packet_order;
mod packet_order_set_carried_item;
mod receive_spawn_entity_and_start_config_packet;
mod receive_start_config_packet;
mod reply_to_ping_with_pong;
mod set_health_before_login;
mod teleport_movement;
mod ticks_alive;
