[build]
rustflags = [
  "--cfg", "docsrs_dep",
  "-Znext-solver=coherence" # This is temporary until the new trait solver supports `min_const_generic`s
]
rustdocflags = [
    "--html-after-content",
    "docs-rs/trait-tags.html",
    "--html-after-content",
    "docs-rs/arborium-header.html",
    "--cfg",
    "docsrs_dep",
]

[unstable]
rustdoc-scrape-examples = true
