from lib.utils import to_snake_case, upper_first_letter, get_dir_location, to_camel_case

REGISTRIES_DIR = get_dir_location("../azalea-registry/src/tags")


def generate_tags(registries: dict, file_name: str, struct_name: str):
    tags_dir = f"{REGISTRIES_DIR}/{file_name}.rs"

    generated = f"""// This file was @generated by codegen/lib/code/tags.py, don't edit it manually!

use std::sync::LazyLock;

use crate::{{builtin::{struct_name}, tags::RegistryTag}};

"""

    for tag_name, tag in sorted(registries.items(), key=lambda x: x[0]):
        entries = []
        queue = tag["values"].copy()
        while queue != []:
            ident = queue.pop(0)
            namespace, entry_name = ident.split(":")
            if namespace[0] == "#":
                queue += registries[entry_name]["values"]
                continue
            entries.append(entry_name)

        tag_name = tag_name.replace("/", "_")
        static_set_name = to_snake_case(tag_name).upper()
        generated += f"pub static {static_set_name}: LazyLock<RegistryTag<{struct_name}>> = LazyLock::new(|| RegistryTag::new(vec!["

        # this is important because we binary search registries in some cases
        entries.sort()

        for entry_name in entries:
            generated += (
                f"{struct_name}::{upper_first_letter(to_camel_case(entry_name))},\n"
            )
        generated += "]));\n"

    with open(tags_dir, "w") as f:
        f.write(generated)
