use std::{
    fs::{self, File},
    io::Write,
};

fn main() {
    // Tell Cargo that if the given file changes, to rerun this build script.
    println!("cargo::rerun-if-changed=tests");

    let Ok(paths) = fs::read_dir("tests/simulation") else {
        return;
    };

    let mut modules = Vec::new();

    for path in paths {
        let Ok(path) = path else {
            continue;
        };
        let path = path.path();
        if path.extension().is_none_or(|ext| ext != "rs") {
            continue;
        }
        let mod_name = path.with_extension("");
        let mod_name = mod_name.file_name().unwrap().to_string_lossy().to_string();
        if mod_name == "mod" {
            continue;
        }
        modules.push(mod_name);
    }

    let Ok(mut mod_rs) = File::create("tests/simulation/mod.rs") else {
        return;
    };
    let _ = writeln!(
        mod_rs,
        "// This file is @generated by `azalea-client/build.rs`.\n"
    );
    modules.sort();
    for mod_name in modules {
        let _ = writeln!(mod_rs, "mod {mod_name};");
    }
}
